# -*- coding: utf-8 -*-
"""
Tillar Alifbosi (Alphabet) boyitilgan ma'lumotlar bazasi:
- Ingliz tili (en)
- Rus tili (ru)
- Koreys tili (ko) - Hangul
- Turk tili (tr)
- O'zbek tili (uz) - Lotin va Kirill
- Arab tili (ar) - Huruf al-hijoiyya
- Nemis tili (de) - Deutsche Alphabet
- Fransuz tili (fr) - Alphabet Français
- Yapon tili (ja) - Hiragana va Katakana
"""

ALPHABET_DATA = {
    "en": (
        "🇬🇧 <b>INGLIZ TILI ALIFBOSI (ENGLISH ALPHABET)</b>\n\n"
        "Ingliz alifbosida <b>26 ta harf</b> mavjud (5 ta unli, 21 ta undosh):\n\n"
        "• <b>Aa</b> [ey] — <i>Apple</i> (Olma)\n"
        "• <b>Bb</b> [bi:] — <i>Book</i> (Kitob)\n"
        "• <b>Cc</b> [si:] — <i>Cat</i> (Mushuk)\n"
        "• <b>Dd</b> [di:] — <i>Dog</i> (It)\n"
        "• <b>Ee</b> [i:] — <i>Elephant</i> (Fil)\n"
        "• <b>Ff</b> [ef] — <i>Fish</i> (Baliq)\n"
        "• <b>Gg</b> [dji:] — <i>Girl</i> (Qiz)\n"
        "• <b>Hh</b> [eych] — <i>House</i> (Uy)\n"
        "• <b>Ii</b> [ay] — <i>Ice</i> (Muz)\n"
        "• <b>Jj</b> [djey] — <i>Juice</i> (Sharbat)\n"
        "• <b>Kk</b> [key] — <i>King</i> (Qirol)\n"
        "• <b>Ll</b> [el] — <i>Lion</i> (Sher)\n"
        "• <b>Mm</b> [em] — <i>Mother</i> (Ona)\n"
        "• <b>Nn</b> [en] — <i>Night</i> (Tun)\n"
        "• <b>Oo</b> [ou] — <i>Orange</i> (Apelsin)\n"
        "• <b>Pp</b> [pi:] — <i>Pen</i> (Ruchka)\n"
        "• <b>Qq</b> [kyu:] — <i>Queen</i> (Qirolicha)\n"
        "• <b>Rr</b> [a:] — <i>Rain</i> (Yomg'ir)\n"
        "• <b>Ss</b> [es] — <i>Sun</i> (Quyosh)\n"
        "• <b>Tt</b> [ti:] — <i>Tea</i> (Choy)\n"
        "• <b>Uu</b> [yu:] — <i>Umbrella</i> (Soyabon)\n"
        "• <b>Vv</b> [vi:] — <i>Voice</i> (Ovoz)\n"
        "• <b>Ww</b> [dabl-yu] — <i>Water</i> (Suv)\n"
        "• <b>Xx</b> [eks] — <i>Box</i> (Quti)\n"
        "• <b>Yy</b> [way] — <i>Yellow</i> (Sariq)\n"
        "• <b>Zz</b> [zed / zi:] — <i>Zoo</i> (Hayvonot bog'i)\n\n"
        "💡 <b>Muhim tovush birikmalari:</b>\n"
        "• <b>sh</b> [sh] — <i>she, ship, fish</i>\n"
        "• <b>ch</b> [ch] — <i>chair, cheese, match</i>\n"
        "• <b>th</b> [θ / ð] — <i>think (tillararo s), this (tillararo z)</i>\n"
        "• <b>ph</b> [f] — <i>phone, photo, phantom</i>\n"
        "• <b>ck</b> [k] — <i>black, clock, duck</i>\n"
        "• <b>tion / sion</b> [shn] — <i>nation, action, vision [zhn]</i>\n\n"
        "🔇 <b>O'qilmaydigan harflar (Silent Letters):</b>\n"
        "• <b>k</b>: <i>knee, know, knife</i> (k o'qilmaydi)\n"
        "• <b>w</b>: <i>write, wrong, wrist</i> (w o'qilmaydi)\n"
        "• <b>b</b>: <i>climb, comb, debt</i> (b o'qilmaydi)\n"
        "• <b>l</b>: <i>talk, walk, half</i> (l o'qilmaydi)"
    ),

    "ru": (
        "🇷🇺 <b>RUS TILI ALIFBOSI (РУССКИЙ АЛФАВИТ)</b>\n\n"
        "Rus alifbosida <b>33 ta harf</b> mavjud (10 ta unli, 21 ta undosh, 2 ta belgi):\n\n"
        "• <b>А а</b> [а] — <i>Автобус</i> (Avtobus)\n"
        "• <b>Б б</b> [бэ] — <i>Брат</i> (Aka/uka)\n"
        "• <b>В в</b> [вэ] — <i>Вода</i> (Suv)\n"
        "• <b>Г г</b> [гэ] — <i>Город</i> (Shahar)\n"
        "• <b>Д д</b> [дэ] — <i>Дом</i> (Uy)\n"
        "• <b>Е е</b> [йе / э] — <i>Еда</i> (Ovqat)\n"
        "• <b>Ё ё</b> [йо] — <i>Ёлка</i> (Archa)\n"
        "• <b>Ж ж</b> [жэ] — <i>Жизнь</i> (Hayot)\n"
        "• <b>З з</b> [зэ] — <i>Зима</i> (Qish)\n"
        "• <b>И и</b> [и] — <i>Игра</i> (O'yin)\n"
        "• <b>Й й</b> [и краткое] — <i>Чай</i> (Choy)\n"
        "• <b>К к</b> [ка] — <i>Книга</i> (Kitob)\n"
        "• <b>Л л</b> [эль] — <i>Лето</i> (Yoz)\n"
        "• <b>М м</b> [эм] — <i>Мама</i> (Ona)\n"
        "• <b>Н н</b> [эн] — <i>Небо</i> (Osmon)\n"
        "• <b>О о</b> [о] — <i>Окно</i> (Deraza)\n"
        "• <b>П п</b> [пэ] — <i>Папа</i> (Ota)\n"
        "• <b>Р р</b> [эр] — <i>Работа</i> (Ish)\n"
        "• <b>С с</b> [эс] — <i>Солнце</i> (Quyosh)\n"
        "• <b>Т т</b> [тэ] — <i>Утро</i> (Tong)\n"
        "• <b>У у</b> [у] — <i>Ученик</i> (O'quvchi)\n"
        "• <b>Ф ф</b> [эф] — <i>Фото</i> (Rasm)\n"
        "• <b>Х х</b> [ха] — <i>Хлеб</i> (Non)\n"
        "• <b>Ц ц</b> [цэ] — <i>Цветок</i> (Gul)\n"
        "• <b>Ч ч</b> [че] — <i>Часы</i> (Soat)\n"
        "• <b>Ш ш</b> [ша (qattiq)] — <i>Школа</i> (Maktab)\n"
        "• <b>Щ щ</b> [ща (yumshoq)] — <i>Щетка</i> (Cho'tka)\n"
        "• <b>Ъ ъ</b> [твёрдый знак] — <i>Объект</i> (Qattiqlik belgisi)\n"
        "• <b>Ы ы</b> [ы (qattiq i)] — <i>Сын</i> (O'g'il)\n"
        "• <b>Ь ь</b> [мягкий знак] — <i>День</i> (Yumshatish belgisi)\n"
        "• <b>Э э</b> [э] — <i>Этот</i> (Bu)\n"
        "• <b>Ю ю</b> [йу] — <i>Юг</i> (Janub)\n"
        "• <b>Я я</b> [йа] — <i>Яблоко</i> (Olma)\n\n"
        "💡 <b>Muhim fonetik qoidalar:</b>\n"
        "• <b>Е, Ё, Ю, Я</b> so'z boshida va unlilardan keyin [y] tovushi bilan eshitiladi (йе, йо, йу, йа).\n"
        "• <b>О</b> harfiga urg'u tushmasa, u [а] kabi talaffuz qilinadi (masalan: <i>молоко</i> -> [малако]).\n"
        "• <b>Ж, Ш, Ц</b> har doim qattiq, <b>Ч, Щ, Й</b> har doim yumshoq talaffuz qilinadi."
    ),

    "ko": (
        "🇰🇷 <b>KOREYS TILI ALIFBOSI (HANGEUL / 한글)</b>\n\n"
        "Koreys alifbosi 1443-yilda Buyuk Qirol Sejong tomonidan yaratilgan. U juda mantiqiy va o'rganish oson!\n\n"
        "🔴 <b>Asosiy Unlilar (기본 모음 - 10 ta):</b>\n"
        "• <b>ㅏ</b> [a] — 아버지 (Ota)\n"
        "• <b>ㅑ</b> [ya] — 야구 (Beysbol)\n"
        "• <b>ㅓ</b> [o (ochiq, keng)] — 어머니 (Ona)\n"
        "• <b>ㅕ</b> [yo (ochiq)] — 여기 (Bu yer)\n"
        "• <b>ㅗ</b> [o (lablangan, yopiq)] — 오늘 (Bugun)\n"
        "• <b>ㅛ</b> [yo (lablangan)] — 요리 (Oshpazlik)\n"
        "• <b>ㅜ</b> [u] — 우유 (Sut)\n"
        "• <b>ㅠ</b> [yu] — 유리 (Shisha)\n"
        "• <b>ㅡ</b> [i (tishlarni jipslashtirib)] — 그림 (Rasm)\n"
        "• <b>ㅣ</b> [i] — 이름 (Ism)\n\n"
        "🟡 <b>Qo'shaloq unlilar (11 ta):</b>\n"
        "• <b>ㅐ</b> [e] | <b>ㅔ</b> [e] | <b>ㅒ</b> [ye] | <b>ㅖ</b> [ye]\n"
        "• <b>ㅘ</b> [wa] | <b>ㅙ</b> [we] | <b>ㅚ</b> [we] | <b>ㅝ</b> [wo]\n"
        "• <b>ㅞ</b> [we] | <b>ㅟ</b> [wi] | <b>ㅢ</b> [iy / e]\n\n"
        "🔵 <b>Asosiy Undoshlar (기본 자음 - 14 ta):</b>\n"
        "• <b>ㄱ</b> [k / g] — 가방 (Sumka)\n"
        "• <b>ㄴ</b> [n] — 나라 (Mamlakat)\n"
        "• <b>ㄷ</b> [t / d] — 다리 (Ko'prik/Oyoq)\n"
        "• <b>ㄹ</b> [r / l] — 라디오 (Radio)\n"
        "• <b>ㅁ</b> [m] — 마음 (Ko'ngil)\n"
        "• <b>ㅂ</b> [p / b] — 바다 (Dengiz)\n"
        "• <b>ㅅ</b> [s] — 사람 (Odam)\n"
        "• <b>ㅇ</b> [boshida o'qilmaydi / oxirida 'ng'] — 아이 (Bola), 강 (Daryo)\n"
        "• <b>ㅈ</b> [ch / j] — 지도 (Xarita)\n"
        "• <b>ㅊ</b> [ch' (havoli)] — 친구 (Do'st)\n"
        "• <b>ㅋ</b> [k' (havoli)] — 커피 (Kofe)\n"
        "• <b>ㅌ</b> [t' (havoli)] — 토마토 (Pomidor)\n"
        "• <b>ㅍ</b> [p' (havoli)] — 포도 (Uzum)\n"
        "• <b>ㅎ</b> [h] — 하늘 (Osmon)\n\n"
        "🟣 <b>Qattiq qo'shaloq undoshlar (쌍자음 - 5 ta):</b>\n"
        "• <b>ㄲ</b> [kk] | <b>ㄸ</b> [tt] | <b>ㅃ</b> [pp] | <b>ㅆ</b> [ss] | <b>ㅉ</b> [jj]\n\n"
        "💡 <b>Batchim (받침):</b> Bo'g'in ostida keluvchi undoshlar qoidasi:\n"
        "ㄱ, ㅋ, ㄲ bo'g'in ostida [k] o'qiladi; ㄷ, ㅅ, ㅈ, ㅊ, ㅌ, ㅎ bo'g'in ostida [t] o'qiladi."
    ),

    "tr": (
        "🇹🇷 <b>TURK TILI ALIFBOSI (TÜRK ALFABESİ)</b>\n\n"
        "Turk alifbosi lotin grafikasiga asoslangan bo'lib, <b>29 ta harf</b>dan iborat (8 ta unli, 21 ta undosh):\n\n"
        "• <b>Aa</b> [a] — <i>Arkadaş</i> (Do'st)\n"
        "• <b>Bb</b> [b] — <i>Baba</i> (Ota)\n"
        "• <b>Cc</b> [j] — <i>Cami</i> (Masjid)\n"
        "• <b>Çç</b> [ch] — <i>Çay</i> (Choy)\n"
        "• <b>Dd</b> [d] — <i>Deniz</i> (Dengiz)\n"
        "• <b>Ee</b> [e] — <i>Ev</i> (Uy)\n"
        "• <b>Ff</b> [f] — <i>Fikir</i> (Fikr)\n"
        "• <b>Gg</b> [g] — <i>Göz</i> (Ko'z)\n"
        "• <b>Ğğ</b> [yumshoq g — o'qilmaydi, unlini cho'zadi] — <i>Dağ</i> (Tog')\n"
        "• <b>Hh</b> [h] — <i>Hava</i> (Havo)\n"
        "• <b>Iı</b> [nuqtasiz i — qattiq 'i'] — <i>Irmak</i> (Daryo)\n"
        "• <b>İi</b> [nuqtali i — oddiy 'i'] — <i>İş</i> (Ish)\n"
        "• <b>Jj</b> [zh] — <i>Jilet</i> (Jilet)\n"
        "• <b>Kk</b> [k] — <i>Kitap</i> (Kitob)\n"
        "• <b>Ll</b> [l] — <i>Limon</i> (Limon)\n"
        "• <b>Mm</b> [m] — <i>Masa</i> (Stol)\n"
        "• <b>Nn</b> [n] — <i>Namaz</i> (Namoz)\n"
        "• <b>Oo</b> [o] — <i>Okul</i> (Maktab)\n"
        "• <b>Öö</b> [ingichka o' — nemischadagi kabi] — <i>Öğrenci</i> (Talaba)\n"
        "• <b>Pp</b> [p] — <i>Para</i> (Pul)\n"
        "• <b>Rr</b> [r] — <i>Renk</i> (Rang)\n"
        "• <b>Ss</b> [s] — <i>Su</i> (Suv)\n"
        "• <b>Şş</b> [sh] — <i>Şehir</i> (Shahar)\n"
        "• <b>Tt</b> [t] — <i>Top</i> (Koptok)\n"
        "• <b>Uu</b> [u] — <i>Uçak</i> (Samolyot)\n"
        "• <b>Üü</b> [ingichka u' — fransuzcha u kabi] — <i>Üzüm</i> (Uzum)\n"
        "• <b>Vv</b> [v] — <i>Vatan</i> (Vatan)\n"
        "• <b>Yy</b> [y] — <i>Yol</i> (Yo'l)\n"
        "• <b>Zz</b> [z] — <i>Zaman</i> (Vaqt)\n\n"
        "💡 <b>Maxsus harflar va uyg'unlik:</b>\n"
        "• <b>C</b> = [j] | <b>Ç</b> = [ch] | <b>Ş</b> = [sh]\n"
        "• <b>I</b> (nuqtasiz) = qattiq 'i' | <b>İ</b> (nuqtali) = yumshoq 'i'\n"
        "• <b>Qattiq unlilar:</b> A, I, O, U | <b>Yumshoq unlilar:</b> E, İ, Ö, Ü\n"
        "• <b>Undoshlar yumshashi:</b> p -> b, ç -> c, t -> d, k -> ğ (Kitap -> Kitabı)."
    ),

    "uz": (
        "🇺🇿 <b>O'ZBEK TILI ALIFBOSI (LOTIN VA KIRILL)</b>\n\n"
        "O'zbek adabiy tilida ham Lotin, ham Kirill yozuvlaridan keng foydalaniladi.\n\n"
        "📌 <b>1. O'ZBEK LOTIN ALIFBOSI (29 ta harf va birikma):</b>\n"
        "• <b>Aa</b> — <i>Anor</i> | <b>Bb</b> — <i>Buloq</i> | <b>Dd</b> — <i>Daraxt</i>\n"
        "• <b>Ee</b> — <i>Eshik</i> | <b>Ff</b> — <i>Farishta</i> | <b>Gg</b> — <i>Gul</i>\n"
        "• <b>Hh</b> — <i>Havo</i> | <b>Ii</b> — <i>Ipak</i> | <b>Jj</b> — <i>Jahon</i>\n"
        "• <b>Kk</b> — <i>Kitob</i> | <b>Ll</b> — <i>Lola</i> | <b>Mm</b> — <i>Maktab</i>\n"
        "• <b>Nn</b> — <i>Non</i> | <b>Oo</b> — <i>Oila</i> | <b>Pp</b> — <i>Paxta</i>\n"
        "• <b>Qq</b> — <i>Quyosh</i> | <b>Rr</b> — <i>Rahmat</i> | <b>Ss</b> — <i>Salom</i>\n"
        "• <b>Tt</b> — <i>Tinchlik</i> | <b>Uu</b> — <i>Umr</i> | <b>Vv</b> — <i>Vatan</i>\n"
        "• <b>Xx</b> — <i>Xalq</i> | <b>Yy</b> — <i>Yulduz</i> | <b>Zz</b> — <i>Zamin</i>\n"
        "• <b>Oʻ oʻ</b> — <i>Oʻzbekiston</i> | <b>Gʻ gʻ</b> — <i>Gʻalaba</i>\n"
        "• <b>Sh sh</b> — <i>Shahar</i> | <b>Ch ch</b> — <i>Choy</i> | <b>Ng ng</b> — <i>Tong</i>\n\n"
        "📌 <b>2. O'ZBEK KIRILL ALIFBOSI (35 ta harf):</b>\n"
        "А, Б, В, Г, Д, Е, Ё, Ж, З, И, Й, К, Л, М, Н, О, П, Р, С, Т, У, Ф, Х, Ц, Ч, Ш, Ъ, Ь, Э, Ю, Я, Ў, Қ, Ғ, Ҳ\n\n"
        "💡 <b>Qoidalar:</b>\n"
        "• <b>Tutuq belgisi (')</b>: unlini cho'zadi (e'lon, ma'no) yoki unlini ajratadi (in'om, san'at).\n"
        "• <b>H</b> (tomoq tovushi - havo, havas) va <b>X</b> (chuqur til orqa - xalq, xat) farqlanadi.\n"
        "• <b>J</b> harfi o'zbek tilida 2 xil: qorishiq [dj] (jo'ja) va sirg'aluvchi [zh] (jurnal)."
    ),

    "ar": (
        "🇸🇦 <b>ARAB TILI ALIFBOSI (HURUF AL-HIJOIYYA / الحروف الهجائية)</b>\n\n"
        "Arab yozuvi <b>o'ngdan chapga</b> qarab yoziladi va <b>28 ta harf</b>dan iborat. Harflar so'zdagi o'rniga qarab o'zgaradi:\n\n"
        "• <b>ا (Alif)</b> — [a / aa]\n"
        "• <b>ب (Ba)</b> — [b]\n"
        "• <b>ت (Ta)</b> — [t]\n"
        "• <b>ث (Sa)</b> — [s (tillararo, ingichka)]\n"
        "• <b>ج (Jim)</b> — [j]\n"
        "• <b>ح (Ha)</b> — [h (tomoq o'rtasidan chiquvchi 'h')]\n"
        "• <b>خ (Xo)</b> — [x (yo'g'on x)]\n"
        "• <b>د (Dal)</b> — [d]\n"
        "• <b>ذ (Zal)</b> — [z (tillararo)]\n"
        "• <b>ر (Ro)</b> — [r (yo'g'on)]\n"
        "• <b>ز (Za)</b> — [z]\n"
        "• <b>س (Sin)</b> — [s]\n"
        "• <b>ش (Shin)</b> — [sh]\n"
        "• <b>ص (Sod)</b> — [s (yo'g'on s)]\n"
        "• <b>ض (Dod)</b> — [d (yo'g'on d)]\n"
        "• <b>ط (To)</b> — [t (yo'g'on t)]\n"
        "• <b>ظ (Zo)</b> — [z (yo'g'on z)]\n"
        "• <b>ع (Ayn)</b> — [‘ (bo'g'iz tovushi)]\n"
        "• <b>غ (G'oyn)</b> — [g' (yo'g'on g')]\n"
        "• <b>ف (Fa)</b> — [f]\n"
        "• <b>ق (Qof)</b> — [q (yo'g'on q)]\n"
        "• <b>ك (Kaf)</b> — [k (yumshoq)]\n"
        "• <b>ل (Lam)</b> — [l]\n"
        "• <b>م (Mim)</b> — [m]\n"
        "• <b>ن (Nun)</b> — [n]\n"
        "• <b>هـ (Ha)</b> — [h (ko'krakdan chiqadigan 'h')]\n"
        "• <b>و (Vav)</b> — [w / u:]\n"
        "• <b>ي (Ya)</b> — [y / i:]\n\n"
        "💡 <b>Harakatlar (Unlilar):</b>\n"
        "Arab tilida qisqa unlilar harflar usti va ostiga qo'yiluvchi belgilar bilan ifodalanadi:\n"
        "• <b>Fatha ( َ )</b> = [a]\n"
        "• <b>Kasra ( ِ )</b> = [i]\n"
        "• <b>Damma ( ُ )</b> = [u]\n"
        "• <b>Sukun ( ْ )</b> = to'xtash (unlisiz undosh)\n"
        "• <b>Shadda ( ّ )</b> = harfni ikkilantirish"
    ),

    "de": (
        "🇩🇪 <b>NEMIS TILI ALIFBOSI (DEUTSCHE ALPHABET)</b>\n\n"
        "Nemis alifbosi lotin yozuvidagi <b>26 ta asosiy harf</b> va <b>4 ta maxsus belgi</b>dan (3 ta Umlaut va 1 ta Eszett) iborat:\n\n"
        "• <b>Aa</b> [a:] — <i>Apfel</i> (Olma)\n"
        "• <b>Bb</b> [be:] — <i>Buch</i> (Kitob)\n"
        "• <b>Cc</b> [tse:] — <i>Computer</i> (Kompyuter)\n"
        "• <b>Dd</b> [de:] — <i>Danke</i> (Rahmat)\n"
        "• <b>Ee</b> [e:] — <i>Eltern</i> (Ota-ona)\n"
        "• <b>Ff</b> [ef] — <i>Freund</i> (Do'st)\n"
        "• <b>Gg</b> [ge:] — <i>Gut</i> (Yaxshi)\n"
        "• <b>Hh</b> [ha:] — <i>Haus</i> (Uy)\n"
        "• <b>Ii</b> [i:] — <i>Igel</i> (Kirpi)\n"
        "• <b>Jj</b> [yot] — <i>Jahr</i> (Yil)\n"
        "• <b>Kk</b> [ka:] — <i>Kind</i> (Bola)\n"
        "• <b>Ll</b> [el] — <i>Leben</i> (Hayot)\n"
        "• <b>Mm</b> [em] — <i>Mutter</i> (Ona)\n"
        "• <b>Nn</b> [en] — <i>Nacht</i> (Tun)\n"
        "• <b>Oo</b> [o:] — <i>Oma</i> (Buvi)\n"
        "• <b>Pp</b> [pe:] — <i>Pause</i> (Tanaffus)\n"
        "• <b>Qq</b> [ku:] — <i>Quelle</i> (Buloq)\n"
        "• <b>Rr</b> [er] — <i>Rot</i> (Qizil)\n"
        "• <b>Ss</b> [es] — <i>Sonne</i> (Quyosh)\n"
        "• <b>Tt</b> [te:] — <i>Tag</i> (Kun)\n"
        "• <b>Uu</b> [u:] — <i>Uhr</i> (Soat)\n"
        "• <b>Vv</b> [fau — ko'pincha 'f' o'qiladi] — <i>Vater</i> (Ota)\n"
        "• <b>Ww</b> [ve: — 'v' o'qiladi] — <i>Wasser</i> (Suv)\n"
        "• <b>Xx</b> [iks] — <i>Taxi</i> (Taksi)\n"
        "• <b>Yy</b> [ypsilon] — <i>System</i> (Tizim)\n"
        "• <b>Zz</b> [tset — har doim 'ts' o'qiladi] — <i>Zeit</i> (Vaqt)\n\n"
        "🟡 <b>Maxsus harflar (Umlaute &amp; Eszett):</b>\n"
        "• <b>Ä ä</b> [e / ae] — <i>Äpfel</i> (Olmalar)\n"
        "• <b>Ö ö</b> [yumshoq o'] — <i>Öl</i> (Yog')\n"
        "• <b>Ü ü</b> [yumshoq u'] — <i>Über</i> (Haqida/Ustida)\n"
        "• <b>ß</b> [qo'shaloq s (Eszett)] — <i>Straße</i> (Ko'cha)\n\n"
        "💡 <b>Muhim tovush birikmalari:</b>\n"
        "• <b>ei</b> [ay] — <i>nein, mein</i>\n"
        "• <b>ie</b> [uzun i:] — <i>sie, wie</i>\n"
        "• <b>eu / äu</b> [oy] — <i>heute, Häuser</i>\n"
        "• <b>sch</b> [sh] — <i>Schule</i> | <b>ch</b> [x / x'] — <i>Buch, ich</i>\n"
        "• <b>sp / st</b> [shp / sht] — <i>Sport, Stadt</i>"
    ),

    "fr": (
        "🇫🇷 <b>FRANSUZ TILI ALIFBOSI (ALPHABET FRANÇAIS)</b>\n\n"
        "Fransuz alifbosi <b>26 ta asosiy harf</b> hamda urg'u va maxsus belgilardan iborat:\n\n"
        "• <b>Aa</b> [a] — <i>Ami</i> (Do'st)\n"
        "• <b>Bb</b> [be] — <i>Bonjour</i> (Salom)\n"
        "• <b>Cc</b> [se] — <i>Café</i> (Qahva)\n"
        "• <b>Dd</b> [de] — <i>Date</i> (Sana)\n"
        "• <b>Ee</b> [yo / e] — <i>École</i> (Maktab)\n"
        "• <b>Ff</b> [ef] — <i>Frère</i> (Aka/uka)\n"
        "• <b>Gg</b> [zhe] — <i>Gare</i> (Vokzal)\n"
        "• <b>Hh</b> [ash — hech qachon o'qilmaydi] — <i>Homme</i> (Erkak)\n"
        "• <b>Ii</b> [i] — <i>Idée</i> (G'oya)\n"
        "• <b>Jj</b> [zhi] — <i>Jour</i> (Kun)\n"
        "• <b>Kk</b> [ka] — <i>Kilo</i> (Kilogramm)\n"
        "• <b>Ll</b> [el] — <i>Livre</i> (Kitob)\n"
        "• <b>Mm</b> [em] — <i>Merci</i> (Rahmat)\n"
        "• <b>Nn</b> [en] — <i>Nuit</i> (Tun)\n"
        "• <b>Oo</b> [o] — <i>Oui</i> (Ha)\n"
        "• <b>Pp</b> [pe] — <i>Pain</i> (Non)\n"
        "• <b>Qq</b> [ku] — <i>Quatre</i> (To'rt)\n"
        "• <b>Rr</b> [er — bo'g'izdan chiquvchi 'r'] — <i>Rouge</i> (Qizil)\n"
        "• <b>Ss</b> [es] — <i>Soleil</i> (Quyosh)\n"
        "• <b>Tt</b> [te] — <i>Train</i> (Poyezd)\n"
        "• <b>Uu</b> [u' (lablar cho'chchaygan)] — <i>Une</i> (Bitta)\n"
        "• <b>Vv</b> [ve] — <i>Ville</i> (Shahar)\n"
        "• <b>Ww</b> [dubl-ve] — <i>Week-end</i> (Dam olish kuni)\n"
        "• <b>Xx</b> [iks] — <i>Taxi</i> (Taksi)\n"
        "• <b>Yy</b> [i-grek] — <i>Yeux</i> (Ko'zlar)\n"
        "• <b>Zz</b> [zed] — <i>Zéro</i> (Nol)\n\n"
        "💡 <b>Maxsus diakritik belgilar:</b>\n"
        "• <b>é (accent aigu)</b> — [yopiq e] — <i>café</i>\n"
        "• <b>è, à, ù (accent grave)</b> — [ochiq e, a, u] — <i>mère, où</i>\n"
        "• <b>ê, â, î, ô, û (circonflexe)</b> — cho'ziqlik beradi — <i>fête, hôtel</i>\n"
        "• <b>ç (cédille)</b> — [s] kabi o'qiladi — <i>français, garçon</i>\n"
        "• <b>Qoida:</b> So'z oxiridagi <b>d, p, s, t, x, z</b> harflari odatda o'qilmaydi (<i>Paris</i> -> Pari)."
    ),

    "ja": (
        "🇯🇵 <b>YAPON TILI ALIFBOSI (HIRAGANA &amp; KATAKANA)</b>\n\n"
        "Yapon tilida 3 xil yozuv turi mavjud: <b>Hiragana</b> (sof yapon so'zlari va grammatika), <b>Katakana</b> (chet tilidan kirgan so'zlar) va <b>Kanji</b> (ierogliflar).\n\n"
        "🔴 <b>HIRAGANA (ひらがな - 46 ta asosiy bo'g'in):</b>\n"
        "• <b>あ (a)</b> | <b>い (i)</b> | <b>う (u)</b> | <b>え (e)</b> | <b>お (o)</b>\n"
        "• <b>か (ka)</b> | <b>き (ki)</b> | <b>く (ku)</b> | <b>け (ke)</b> | <b>こ (ko)</b>\n"
        "• <b>さ (sa)</b> | <b>し (shi)</b> | <b>す (su)</b> | <b>せ (se)</b> | <b>そ (so)</b>\n"
        "• <b>た (ta)</b> | <b>ち (chi)</b> | <b>つ (tsu)</b> | <b>て (te)</b> | <b>と (to)</b>\n"
        "• <b>な (na)</b> | <b>に (ni)</b> | <b>ぬ (nu)</b> | <b>ね (ne)</b> | <b>の (no)</b>\n"
        "• <b>は (ha)</b> | <b>ひ (hi)</b> | <b>ふ (fu)</b> | <b>へ (he)</b> | <b>ほ (ho)</b>\n"
        "• <b>ま (ma)</b> | <b>み (mi)</b> | <b>む (mu)</b> | <b>め (me)</b> | <b>も (mo)</b>\n"
        "• <b>や (ya)</b> | <b>ゆ (yu)</b> | <b>よ (yo)</b>\n"
        "• <b>ら (ra)</b> | <b>り (ri)</b> | <b>る (ru)</b> | <b>れ (re)</b> | <b>ろ (ro)</b>\n"
        "• <b>わ (wa)</b> | <b>を (wo)</b> | <b>ん (n)</b>\n\n"
        "🔵 <b>KATAKANA (カタカナ - Chet so'zlar uchun):</b>\n"
        "• <b>ア (a)</b> | <b>イ (i)</b> | <b>ウ (u)</b> | <b>エ (e)</b> | <b>オ (o)</b>\n"
        "• <b>カ (ka)</b> | <b>キ (ki)</b> | <b>ク (ku)</b> | <b>ケ (ke)</b> | <b>コ (ko)</b>\n"
        "• <b>サ (sa)</b> | <b>シ (shi)</b> | <b>ス (su)</b> | <b>セ (se)</b> | <b>ソ (so)</b>\n"
        "• <b>タ (ta)</b> | <b>チ (chi)</b> | <b>ツ (tsu)</b> | <b>テ (te)</b> | <b>ト (to)</b>\n"
        "• <b>ナ (na)</b> | <b>ニ (ni)</b> | <b>ヌ (nu)</b> | <b>ネ (ne)</b> | <b>ノ (no)</b>\n"
        "• <b>ハ (ha)</b> | <b>ヒ (hi)</b> | <b>フ (fu)</b> | <b>ヘ (he)</b> | <b>ホ (ho)</b>\n"
        "• <b>マ (ma)</b> | <b>ミ (mi)</b> | <b>ム (mu)</b> | <b>メ (me)</b> | <b>モ (mo)</b>\n"
        "• <b>ヤ (ya)</b> | <b>ユ (yu)</b> | <b>ヨ (yo)</b>\n"
        "• <b>ラ (ra)</b> | <b>リ (ri)</b> | <b>ル (ru)</b> | <b>レ (re)</b> | <b>ロ (ro)</b>\n"
        "• <b>ワ (wa)</b> | <b>ヲ (wo)</b> | <b>ン (n)</b>\n\n"
        "💡 <b>Misollar:</b>\n"
        "• ありがとう (Arigatou) = Rahmat\n"
        "• さようなら (Sayounara) = Xayr\n"
        "• コーヒー (Koohii - Katakana) = Kofe"
    ),
}
