# -*- coding: utf-8 -*-
"""
Til o'rganish test savollari bazasi:
- Ingliz tili (en): 100 ta savol
- Rus tili (ru): 100 ta savol
- Koreys tili (ko): 100 ta savol
- Turk tili (tr): 100 ta savol
Jami: 400 ta test savoli.
"""

# ============================================================
# 🇬🇧 INGLIZ TILI TESTLARI (100 ta)
# ============================================================
TEST_QUESTIONS_EN = [
    {"savol": "🇬🇧 'Apple' so'zining o'zbekcha tarjimasi nima?", "variantlar": ["Olma", "Apelsin", "Banan", "Uzum"], "javob": 0, "tushuntirish": "Apple = Olma"},
    {"savol": "🇬🇧 'Book' so'zining o'zbekcha tarjimasi nima?", "variantlar": ["Daftar", "Kitob", "Qalam", "Xat"], "javob": 1, "tushuntirish": "Book = Kitob"},
    {"savol": "🇬🇧 'Water' so'zining ma'nosi nima?", "variantlar": ["Non", "Choy", "Suv", "Sut"], "javob": 2, "tushuntirish": "Water = Suv"},
    {"savol": "🇬🇧 'Beautiful' so'zining ma'nosi nima?", "variantlar": ["Kuchli", "Katta", "Tez", "Chiroyli"], "javob": 3, "tushuntirish": "Beautiful = Chiroyli"},
    {"savol": "🇬🇧 'Sun' so'zining o'zbekchasi qaysi?", "variantlar": ["Quyosh", "Oy", "Yulduz", "Bulut"], "javob": 0, "tushuntirish": "Sun = Quyosh"},
    {"savol": "🇬🇧 'Moon' so'zi nimani anglatadi?", "variantlar": ["Yer", "Oy", "Koinot", "Osmon"], "javob": 1, "tushuntirish": "Moon = Oy"},
    {"savol": "🇬🇧 'Friend' so'zining tarjimasi:", "variantlar": ["Dushman", "Qo'shni", "Do'st", "Aka"], "javob": 2, "tushuntirish": "Friend = Do'st"},
    {"savol": "🇬🇧 'House' nima degani?", "variantlar": ["Bino", "Ko'cha", "Shahar", "Uy"], "javob": 3, "tushuntirish": "House = Uy"},
    {"savol": "🇬🇧 'Car' so'zining o'zbekchasi:", "variantlar": ["Mashina", "Velosiped", "Poyezd", "Samolyot"], "javob": 0, "tushuntirish": "Car = Mashina"},
    {"savol": "🇬🇧 'School' so'zi qaysi ma'noni beradi?", "variantlar": ["Universitet", "Maktab", "Bog'cha", "Kutubxona"], "javob": 1, "tushuntirish": "School = Maktab"},
    {"savol": "🇬🇧 'Teacher' so'zining o'zbekcha tarjimasi:", "variantlar": ["O'quvchi", "Shifokor", "O'qituvchi", "Muhandis"], "javob": 2, "tushuntirish": "Teacher = O'qituvchi"},
    {"savol": "🇬🇧 'Doctor' kasbi o'zbekchada nima deyiladi?", "variantlar": ["Haydovchi", "Oshpaz", "Quruvchi", "Shifokor"], "javob": 3, "tushuntirish": "Doctor = Shifokor"},
    {"savol": "🇬🇧 'Bread' so'zi nima degani?", "variantlar": ["Non", "Go'sht", "Tuxum", "Meva"], "javob": 0, "tushuntirish": "Bread = Non"},
    {"savol": "🇬🇧 'Milk' nimani bildiradi?", "variantlar": ["Sharbat", "Sut", "Qatiq", "Kofe"], "javob": 1, "tushuntirish": "Milk = Sut"},
    {"savol": "🇬🇧 'Tea' so'zining tarjimasi:", "variantlar": ["Suv", "Sharbat", "Choy", "Yog'"], "javob": 2, "tushuntirish": "Tea = Choy"},
    {"savol": "🇬🇧 'City' so'zining ma'nosi:", "variantlar": ["Qishloq", "Tuman", "Viloyat", "Shahar"], "javob": 3, "tushuntirish": "City = Shahar"},
    {"savol": "🇬🇧 'Country' so'zi nima degani?", "variantlar": ["Mamlakat", "Poytaxt", "Okean", "Qit'a"], "javob": 0, "tushuntirish": "Country = Mamlakat / Davlat"},
    {"savol": "🇬🇧 'Family' so'zining o'zbekchasi:", "variantlar": ["Ota-ona", "Oila", "Qarindosh", "Jamoa"], "javob": 1, "tushuntirish": "Family = Oila"},
    {"savol": "🇬🇧 'Time' so'zi nimani anglatadi?", "variantlar": ["Soat", "Kun", "Vaqt", "Yil"], "javob": 2, "tushuntirish": "Time = Vaqt"},
    {"savol": "🇬🇧 'Money' so'zining ma'nosi:", "variantlar": ["Hamyon", "Banka", "Tanga", "Pul"], "javob": 3, "tushuntirish": "Money = Pul"},
    {"savol": "🇬🇧 Bo'sh joyni to'ldiring: 'She ___ a doctor.'", "variantlar": ["is", "are", "am", "be"], "javob": 0, "tushuntirish": "She/He/It uchun 'is' ishlatiladi."},
    {"savol": "🇬🇧 Bo'sh joyni to'ldiring: 'They ___ playing football.'", "variantlar": ["is", "are", "am", "was"], "javob": 1, "tushuntirish": "They ko'plik uchun 'are' ishlatiladi."},
    {"savol": "🇬🇧 Bo'sh joyni to'ldiring: 'I ___ from Uzbekistan.'", "variantlar": ["is", "are", "am", "be"], "javob": 2, "tushuntirish": "I uchun 'am' ishlatiladi."},
    {"savol": "🇬🇧 'Go' fe'lining o'tgan zamon shakli (Past Simple):", "variantlar": ["Goed", "Gone", "Goes", "Went"], "javob": 3, "tushuntirish": "Go noto'g'ri fe'li o'tgan zamonda 'went' bo'ladi."},
    {"savol": "🇬🇧 'Do' fe'lining o'tgan zamon shakli:", "variantlar": ["Did", "Done", "Doing", "Does"], "javob": 0, "tushuntirish": "Do -> Did -> Done."},
    {"savol": "🇬🇧 'Eat' fe'lining o'tgan zamon shakli:", "variantlar": ["Eated", "Ate", "Eaten", "Eating"], "javob": 1, "tushuntirish": "Eat -> Ate -> Eaten."},
    {"savol": "🇬🇧 'See' fe'lining o'tgan zamon shakli:", "variantlar": ["Seed", "Seen", "Saw", "Seeing"], "javob": 2, "tushuntirish": "See -> Saw -> Seen."},
    {"savol": "🇬🇧 'Take' fe'lining o'tgan zamoni:", "variantlar": ["Taked", "Token", "Takes", "Took"], "javob": 3, "tushuntirish": "Take -> Took -> Taken."},
    {"savol": "🇬🇧 'Write' fe'lining o'tgan zamon shakli:", "variantlar": ["Wrote", "Written", "Writed", "Writing"], "javob": 0, "tushuntirish": "Write -> Wrote -> Written."},
    {"savol": "🇬🇧 'Speak' fe'lining o'tgan zamoni:", "variantlar": ["Speaked", "Spoke", "Spoken", "Speaks"], "javob": 1, "tushuntirish": "Speak -> Spoke -> Spoken."},
    {"savol": "🇬🇧 'Good' so'zining qiyosiy darajasi (comparative):", "variantlar": ["Gooder", "More good", "Better", "Best"], "javob": 2, "tushuntirish": "Good -> Better -> Best."},
    {"savol": "🇬🇧 'Bad' so'zining orttirma darajasi (superlative):", "variantlar": ["Badder", "Baddest", "Worse", "Worst"], "javob": 3, "tushuntirish": "Bad -> Worse -> Worst."},
    {"savol": "🇬🇧 'Big' so'zining qiyosiy darajasi:", "variantlar": ["Bigger", "More big", "Biggest", "Bigly"], "javob": 0, "tushuntirish": "Big -> Bigger -> Biggest."},
    {"savol": "🇬🇧 'Fast' so'zining antonimi (qarama-qarshi ma'nosi):", "variantlar": ["Quick", "Slow", "Hard", "Soft"], "javob": 1, "tushuntirish": "Fast (tez) ↔ Slow (sekin)."},
    {"savol": "🇬🇧 'Happy' so'zining antonimi:", "variantlar": ["Joyful", "Kind", "Sad", "Rich"], "javob": 2, "tushuntirish": "Happy (xursand) ↔ Sad (xafa)."},
    {"savol": "🇬🇧 'Hot' so'zining antonimi:", "variantlar": ["Warm", "Fire", "Sunny", "Cold"], "javob": 3, "tushuntirish": "Hot (issiq) ↔ Cold (sovuq)."},
    {"savol": "🇬🇧 'Rich' so'zining antonimi:", "variantlar": ["Poor", "Wealthy", "Cheap", "Hard"], "javob": 0, "tushuntirish": "Rich (boy) ↔ Poor (kambag'al)."},
    {"savol": "🇬🇧 'Difficult' so'zining sinonimi:", "variantlar": ["Easy", "Hard", "Simple", "Light"], "javob": 1, "tushuntirish": "Difficult = Hard (qiyin)."},
    {"savol": "🇬🇧 'Quick' so'zining sinonimi:", "variantlar": ["Slow", "Heavy", "Fast", "Late"], "javob": 2, "tushuntirish": "Quick = Fast (tez)."},
    {"savol": "🇬🇧 'Silent' so'zining ma'nosi:", "variantlar": ["Shovqinli", "Baland", "Kulmali", "Tinch, jim"], "javob": 3, "tushuntirish": "Silent = Tinch, jim-jit."},
    {"savol": "🇬🇧 'Always' so'zining o'zbekchasi:", "variantlar": ["Har doim", "Hech qachon", "Ba'zan", "Kamdan-kam"], "javob": 0, "tushuntirish": "Always = Har doim."},
    {"savol": "🇬🇧 'Never' so'zi nimani bildiradi?", "variantlar": ["Tez-tez", "Hech qachon", "Har doim", "Ehtimol"], "javob": 1, "tushuntirish": "Never = Hech qachon."},
    {"savol": "🇬🇧 'Sometimes' so'zining ma'nosi:", "variantlar": ["Har kuni", "Hech qachon", "Ba'zida", "Doimo"], "javob": 2, "tushuntirish": "Sometimes = Ba'zida / Vaqti-vaqti bilan."},
    {"savol": "🇬🇧 'Often' so'zining tarjimasi:", "variantlar": ["Kamdan-kam", "Hech qachon", "Kechqurun", "Tez-tez"], "javob": 3, "tushuntirish": "Often = Tez-tez."},
    {"savol": "🇬🇧 'Today' so'zining ma'nosi:", "variantlar": ["Bugun", "Kecha", "Ertaga", "Hozir"], "javob": 0, "tushuntirish": "Today = Bugun."},
    {"savol": "🇬🇧 'Tomorrow' nima degani?", "variantlar": ["Bugun", "Ertaga", "Kecha", "Indinga"], "javob": 1, "tushuntirish": "Tomorrow = Ertaga."},
    {"savol": "🇬🇧 'Yesterday' so'zi qaysi kunni bildiradi?", "variantlar": ["Bugun", "Ertaga", "Kecha", "O'tgan hafta"], "javob": 2, "tushuntirish": "Yesterday = Kecha."},
    {"savol": "🇬🇧 'Now' so'zi nimani anglatadi?", "variantlar": ["Keyin", "Ilgari", "Ertalab", "Hozir"], "javob": 3, "tushuntirish": "Now = Hozir."},
    {"savol": "🇬🇧 'Before' so'zining tarjimasi:", "variantlar": ["Oldin", "Keyin", "Hozir", "Bilan"], "javob": 0, "tushuntirish": "Before = Oldin."},
    {"savol": "🇬🇧 'After' so'zi nimani anglatadi?", "variantlar": ["Oldin", "Keyin", "Ichida", "Yonida"], "javob": 1, "tushuntirish": "After = Keyin."},
    {"savol": "🇬🇧 'Between' so'zining ma'nosi:", "variantlar": ["Ustida", "Ostida", "O'rtasida", "Yaqinida"], "javob": 2, "tushuntirish": "Between = Ikki narsaning o'rtasida."},
    {"savol": "🇬🇧 'Under' so'zi nimani bildiradi?", "variantlar": ["Ustida", "Ichida", "Orqasida", "Tagida, ostida"], "javob": 3, "tushuntirish": "Under = Ostida, tagida."},
    {"savol": "🇬🇧 'Above' so'zi nima degani?", "variantlar": ["Tepasida", "Tagida", "Yonginasida", "Orqasida"], "javob": 0, "tushuntirish": "Above = Tepasida, yuqorisida."},
    {"savol": "🇬🇧 'Behind' so'zi qayerda ekanlikni bildiradi?", "variantlar": ["Oldida", "Orqasida", "Ichida", "Uzoqda"], "javob": 1, "tushuntirish": "Behind = Orqasida."},
    {"savol": "🇬🇧 'In front of' iborasining ma'nosi:", "variantlar": ["Orqasida", "Yonida", "Oldida", "Ustida"], "javob": 2, "tushuntirish": "In front of = Ro'parasida, oldida."},
    {"savol": "🇬🇧 'Next to' nima degani?", "variantlar": ["Uzoqda", "Ichida", "Tepasida", "Yonida"], "javob": 3, "tushuntirish": "Next to = Yonida."},
    {"savol": "🇬🇧 'Knowledge' so'zining tarjimasi:", "variantlar": ["Bilim", "Kuch", "Boylik", "Muvaffaqiyat"], "javob": 0, "tushuntirish": "Knowledge = Bilim."},
    {"savol": "🇬🇧 'Success' so'zi nimani anglatadi?", "variantlar": ["Omadsizlik", "Muvaffaqiyat", "Tinchlik", "Imtihon"], "javob": 1, "tushuntirish": "Success = Muvaffaqiyat."},
    {"savol": "🇬🇧 'Opportunity' so'zining tarjimasi:", "variantlar": ["Qiyinchilik", "Vazifa", "Imkoniyat", "Natija"], "javob": 2, "tushuntirish": "Opportunity = Imkoniyat."},
    {"savol": "🇬🇧 'Environment' so'zining ma'nosi:", "variantlar": ["Hukumat", "Iqtisod", "Sanoat", "Atrof-muhit"], "javob": 3, "tushuntirish": "Environment = Atrof-muhit."},
    {"savol": "🇬🇧 'Decision' so'zi nima degani?", "variantlar": ["Qaror", "Fikr", "Savol", "Taklif"], "javob": 0, "tushuntirish": "Decision = Qaror."},
    {"savol": "🇬🇧 'Experience' so'zining tarjimasi:", "variantlar": ["Yosh", "Tajriba", "Bilim", "Kitob"], "javob": 1, "tushuntirish": "Experience = Tajriba."},
    {"savol": "🇬🇧 'Freedom' so'zining ma'nosi:", "variantlar": ["Boylik", "Adolat", "Ozodlik, erkinlik", "Qonun"], "javob": 2, "tushuntirish": "Freedom = Ozodlik, erkinlik."},
    {"savol": "🇬🇧 'Government' so'zining ma'nosi:", "variantlar": ["Xalq", "Sud", "Prezident", "Hukumat"], "javob": 3, "tushuntirish": "Government = Hukumat."},
    {"savol": "🇬🇧 'Health' so'zi nimani anglatadi?", "variantlar": ["Salomatlik", "Baxt", "Uyqu", "Ovqat"], "javob": 0, "tushuntirish": "Health = Salomatlik, sog'liq."},
    {"savol": "🇬🇧 'Peace' so'zining o'zbekchasi:", "variantlar": ["Urush", "Tinchlik", "G'alaba", "Kelishuv"], "javob": 1, "tushuntirish": "Peace = Tinchlik."},
    {"savol": "🇬🇧 'Hope' so'zi nimani bildiradi?", "variantlar": ["Qo'rquv", "G'am", "Umid", "Sevgi"], "javob": 2, "tushuntirish": "Hope = Umid."},
    {"savol": "🇬🇧 'Believe' fe'lining ma'nosi:", "variantlar": ["Uxlash", "O'ylash", "Kutish", "Ishonmoq"], "javob": 3, "tushuntirish": "Believe = Ishonmoq."},
    {"savol": "🇬🇧 'Understand' so'zining tarjimasi:", "variantlar": ["Tushunmoq", "Eshitmoq", "Gapirmoq", "Ko'rmoq"], "javob": 0, "tushuntirish": "Understand = Tushunmoq."},
    {"savol": "🇬🇧 'Remember' fe'li nima degani?", "variantlar": ["Unitmoq", "Eslab qolmoq", "Qidirmoq", "Yo'qotmoq"], "javob": 1, "tushuntirish": "Remember = Eslamoq, eslab qolmoq."},
    {"savol": "🇬🇧 'Forget' fe'lining o'zbekchasi:", "variantlar": ["Eslamoq", "Yozmoq", "Unitmoq", "Topmoq"], "javob": 2, "tushuntirish": "Forget = Unitmoq."},
    {"savol": "🇬🇧 'Improve' so'zi nimani bildiradi?", "variantlar": ["Buzmoq", "Kamaytirmoq", "Qaytarmoq", "Yaxshilamoq"], "javob": 3, "tushuntirish": "Improve = Rivojlantirmoq, yaxshilamoq."},
    {"savol": "🇬🇧 'Develop' so'zining tarjimasi:", "variantlar": ["Rivojlanmoq", "To'xtamoq", "Yo'qolmoq", "Kechikmoq"], "javob": 0, "tushuntirish": "Develop = Rivojlanmoq, rivojlantirmoq."},
    {"savol": "🇬🇧 'Achieve' fe'lining ma'nosi:", "variantlar": ["Yutqazmoq", "Erishmoq", "Qochmoq", "Voz kechmoq"], "javob": 1, "tushuntirish": "Achieve = Erishmoq, qo'lga kiritmoq."},
    {"savol": "🇬🇧 'Discover' so'zining tarjimasi:", "variantlar": ["Yashirmoq", "Yoqmoq", "Kashf qilmoq", "Sotmoq"], "javob": 2, "tushuntirish": "Discover = Kashf etmoq."},
    {"savol": "🇬🇧 'Create' so'zining o'zbekchasi:", "variantlar": ["Buzmoq", "Charchamoq", "Ko'chirmoq", "Yaratmoq"], "javob": 3, "tushuntirish": "Create = Yaratmoq."},
    {"savol": "🇬🇧 'I am interested ___ learning languages.'", "variantlar": ["in", "at", "on", "about"], "javob": 0, "tushuntirish": "Interested in frazasi ishlatiladi."},
    {"savol": "🇬🇧 'She is good ___ playing chess.'", "variantlar": ["in", "at", "for", "with"], "javob": 1, "tushuntirish": "Good at birikmasi qo'llaniladi."},
    {"savol": "🇬🇧 'Listen ___ me carefully!'", "variantlar": ["for", "at", "to", "with"], "javob": 2, "tushuntirish": "Listen to fe'l birikmasi."},
    {"savol": "🇬🇧 'Wait ___ me at the bus stop.'", "variantlar": ["to", "at", "on", "for"], "javob": 3, "tushuntirish": "Wait for - kutmoq."},
    {"savol": "🇬🇧 'Depends ___ the weather.'", "variantlar": ["on", "in", "to", "at"], "javob": 0, "tushuntirish": "Depend on - bog'liq bo'lmoq."},
    {"savol": "🇬🇧 'Afraid ___ spiders.'", "variantlar": ["from", "of", "with", "by"], "javob": 1, "tushuntirish": "Afraid of - qo'rqmoq."},
    {"savol": "🇬🇧 'Proud ___ his son.'", "variantlar": ["to", "with", "of", "for"], "javob": 2, "tushuntirish": "Proud of - faxrlanmoq."},
    {"savol": "🇬🇧 'Famous ___ its historical monuments.'", "variantlar": ["with", "about", "to", "for"], "javob": 3, "tushuntirish": "Famous for - bilan mashhur."},
    {"savol": "🇬🇧 'How ___ sugar do you want?'", "variantlar": ["much", "many", "few", "any"], "javob": 0, "tushuntirish": "Sanalmaydigan otlar (sugar) uchun 'how much' ishlatiladi."},
    {"savol": "🇬🇧 'How ___ books did you read?'", "variantlar": ["much", "many", "little", "any"], "javob": 1, "tushuntirish": "Sanaladigan ko'plik otlar (books) uchun 'how many' ishlatiladi."},
    {"savol": "🇬🇧 'There are ___ students in the room.'", "variantlar": ["much", "any", "some", "a"], "javob": 2, "tushuntirish": "Ijobiy darak gapda sanaladigan otlar oldidan 'some' qo'yiladi."},
    {"savol": "🇬🇧 'I don't have ___ money.'", "variantlar": ["some", "no", "many", "any"], "javob": 3, "tushuntirish": "Inkor gaplarda 'any' ishlatiladi."},
    {"savol": "🇬🇧 'If it rains, we ___ stay at home.'", "variantlar": ["will", "would", "had", "are"], "javob": 0, "tushuntirish": "First Conditional: If + Present Simple, will + verb."},
    {"savol": "🇬🇧 'Neither Tom ___ Jack came.'", "variantlar": ["and", "nor", "or", "but"], "javob": 1, "tushuntirish": "Neither ... nor birikmasi."},
    {"savol": "🇬🇧 'Either you ___ he must do it.'", "variantlar": ["nor", "and", "or", "both"], "javob": 2, "tushuntirish": "Either ... or birikmasi."},
    {"savol": "🇬🇧 'Although it was late, ___ he kept working.'", "variantlar": ["and", "so", "because", "yet"], "javob": 3, "tushuntirish": "Although gaplarida bog'lovchi mosligi."},
    {"savol": "🇬🇧 'Break a leg' idiomsining ma'nosi nima?", "variantlar": ["Omad tilayman!", "Oyog'ingni sindir", "Ehtiyot bo'l", "Shoshilma"], "javob": 0, "tushuntirish": "'Break a leg' ingliz tilida 'Omad tilayman' (Good luck) degani."},
    {"savol": "🇬🇧 'Piece of cake' iborasi nimani bildiradi?", "variantlar": ["Tort bo'lagi", "Juda oson ish", "Mazali taom", "Qiyin vazifa"], "javob": 1, "tushuntirish": "'Piece of cake' = Juda oson, suv tekin ish."},
    {"savol": "🇬🇧 'Once in a blue moon' iborasining ma'nosi:", "variantlar": ["Har doim", "Kechasi", "Juda kamdan-kam", "To'lin oyda"], "javob": 2, "tushuntirish": "'Once in a blue moon' = Juda kamdan-kam sodir bo'ladigan narsa."},
    {"savol": "🇬🇧 'Under the weather' degani nima?", "variantlar": ["Yomg'ir ostida", "Sovuq qotmoq", "Quyoshda toblanmoq", "O'zini yomon/kasal his qilmoq"], "javob": 3, "tushuntirish": "'Under the weather' = O'zini betob his qilmoq."},
    {"savol": "🇬🇧 'Call it a day' iborasining ma'nosi:", "variantlar": ["Bugungi ishni yakunlamoq", "Kunni rejalashtirmoq", "Qo'ng'iroq qilmoq", "Dam olmaslik"], "javob": 0, "tushuntirish": "'Call it a day' = Bugunga yetadi, ishni tugatdik."},
    {"savol": "🇬🇧 'Cost an arm and a leg' nimani anglatadi?", "variantlar": ["Arzon turmoq", "Juda qimmat bo'lmoq", "Jarohat olmoq", "Sotib ololmaslik"], "javob": 1, "tushuntirish": "'Cost an arm and a leg' = Juda ham qimmat bo'lmoq."},
    {"savol": "🇬🇧 'Hit the books' iborasining ma'nosi:", "variantlar": ["Kitobni urmoq", "Kitob sotib olmoq", "Qattiq dars o'qimoq", "Kutubxonaga bormoq"], "javob": 2, "tushuntirish": "'Hit the books' = Jiddiy dars qilishga kirishmoq."},
    {"savol": "🇬🇧 'Bite the bullet' iborasi nimani bildiradi?", "variantlar": ["O'q yutmoq", "Tish og'rig'i", "Urush boshlamoq", "Qiyinchilikka chidamoq"], "javob": 3, "tushuntirish": "'Bite the bullet' = Noiloj qiyinchilikka chidab yengmoq."},
]

# ============================================================
# 🇷🇺 RUS TILI TESTLARI (100 ta)
# ============================================================
TEST_QUESTIONS_RU = [
    {"savol": "🇷🇺 'Книга' so'zining o'zbekcha tarjimasi nima?", "variantlar": ["Kitob", "Daftar", "Qalam", "Lug'at"], "javob": 0, "tushuntirish": "Книга = Kitob"},
    {"savol": "🇷🇺 'Солнце' so'zi nimani anglatadi?", "variantlar": ["Oy", "Quyosh", "Yulduz", "Bulut"], "javob": 1, "tushuntirish": "Солнце = Quyosh"},
    {"savol": "🇷🇺 'Вода' so'zining ma'nosi:", "variantlar": ["Non", "Choy", "Suv", "Sut"], "javob": 2, "tushuntirish": "Вода = Suv"},
    {"savol": "🇷🇺 'Друг' so'zining tarjimasi:", "variantlar": ["Dushman", "Aka", "Qo'shni", "Do'st"], "javob": 3, "tushuntirish": "Друг = Do'st"},
    {"savol": "🇷🇺 'Дом' so'zining o'zbekchasi qaysi?", "variantlar": ["Uy", "Bino", "Xona", "Ko'cha"], "javob": 0, "tushuntirish": "Дом = Uy"},
    {"savol": "🇷🇺 'Машина' so'zi nima degani?", "variantlar": ["Velosiped", "Mashina", "Poyezd", "Kema"], "javob": 1, "tushuntirish": "Машина = Mashina"},
    {"savol": "🇷🇺 'Школа' so'zining ma'nosi:", "variantlar": ["Bog'cha", "Kutubxona", "Maktab", "Universitet"], "javob": 2, "tushuntirish": "Школа = Maktab"},
    {"savol": "🇷🇺 'Работа' so'zi nimani anglatadi?", "variantlar": ["Dam olish", "Uyqu", "Sayohat", "Ish"], "javob": 3, "tushuntirish": "Работа = Ish"},
    {"savol": "🇷🇺 'Время' so'zining tarjimasi:", "variantlar": ["Vaqt", "Soat", "Kun", "Yil"], "javob": 0, "tushuntirish": "Время = Vaqt"},
    {"savol": "🇷🇺 'Деньги' so'zining ma'nosi:", "variantlar": ["Hamyon", "Pul", "Banka", "Hisob"], "javob": 1, "tushuntirish": "Деньги = Pul"},
    {"savol": "🇷🇺 'Хлеб' so'zi nima degani?", "variantlar": ["Sut", "Go'sht", "Non", "Shakar"], "javob": 2, "tushuntirish": "Хлеб = Non"},
    {"savol": "🇷🇺 'Яблоко' so'zining tarjimasi:", "variantlar": ["Nok", "Uzum", "Anor", "Olma"], "javob": 3, "tushuntirish": "Яблоко = Olma"},
    {"savol": "🇷🇺 'Город' so'zining ma'nosi:", "variantlar": ["Shahar", "Qishloq", "Ko'cha", "Tuman"], "javob": 0, "tushuntirish": "Город = Shahar"},
    {"savol": "🇷🇺 'Страна' nimani bildiradi?", "variantlar": ["Shahar", "Mamlakat", "Qit'a", "Dunyo"], "javob": 1, "tushuntirish": "Страна = Mamlakat / Davlat"},
    {"savol": "🇷🇺 'Семья' so'zining o'zbekchasi:", "variantlar": ["Do'stlar", "Qo'shnilar", "Oila", "Ota-ona"], "javob": 2, "tushuntirish": "Семья = Oila"},
    {"savol": "🇷🇺 'Учитель' so'zi qaysi kasb?", "variantlar": ["Shifokor", "Haydovchi", "Oshpaz", "O'qituvchi"], "javob": 3, "tushuntirish": "Учитель = O'qituvchi"},
    {"savol": "🇷🇺 'Врач' so'zining ma'nosi:", "variantlar": ["Shifokor", "Hamshira", "Dorishunos", "Muhandis"], "javob": 0, "tushuntirish": "Врач = Shifokor / Do'xtir"},
    {"savol": "🇷🇺 'Я ___ книгу.' — to'g'ri fe'lni tanlang:", "variantlar": ["читает", "читаю", "читаем", "читают"], "javob": 1, "tushuntirish": "Я (men) bilan 'читаю' shakli ishlatiladi."},
    {"savol": "🇷🇺 'Он ___ студентом.' — bo'sh joyni to'ldiring:", "variantlar": ["была", "были", "является", "являются"], "javob": 2, "tushuntirish": "Он (u) bilan birlik 'является' qo'llanadi."},
    {"savol": "🇷🇺 'Они ___ в парке.' — to'g'ri fe'l shakli:", "variantlar": ["гуляю", "гуляет", "гуляем", "гуляют"], "javob": 3, "tushuntirish": "Они (ular) ko'plikda 'гуляют'."},
    {"savol": "🇷🇺 'Стол' so'zining jinsi (род) qaysi?", "variantlar": ["Мужской (Muzhskoy)", "Женский (Zhenskiy)", "Средний (Sredniy)", "Jinsi yo'q"], "javob": 0, "tushuntirish": "Undosh bilan tugaydigan 'стол' — Muzhskoy rod."},
    {"savol": "🇷🇺 'Книга' so'zining jinsi qaysi?", "variantlar": ["Мужской", "Женский", "Средний", "Aralash"], "javob": 1, "tushuntirish": "-a bilan tugaydigan 'книга' — Zhenskiy rod."},
    {"savol": "🇷🇺 'Окно' so'zining jinsi qaysi?", "variantlar": ["Мужской", "Женский", "Средний", "Ko'plik"], "javob": 2, "tushuntirish": "-o/-e bilan tugaydigan 'окно' — Sredniy rod."},
    {"savol": "🇷🇺 'Красивый' so'zining ayol jinsi shakli:", "variantlar": ["Красивое", "Красивые", "Красива", "Красивая"], "javob": 3, "tushuntirish": "Zhenskiy rod uchun sifat qo'shimchasi -ая: Красивая."},
    {"savol": "🇷🇺 'Большой' so'zining antonimi (qarama-qarshisi):", "variantlar": ["Маленький", "Огромный", "Высокий", "Широкий"], "javob": 0, "tushuntirish": "Большой (katta) ↔ Маленький (kichik)."},
    {"savol": "🇷🇺 'Быстрый' so'zining antonimi:", "variantlar": ["Скорый", "Медленный", "Громкий", "Тихий"], "javob": 1, "tushuntirish": "Быстрый (tez) ↔ Медленный (sekin)."},
    {"savol": "🇷🇺 'Горячий' so'zining antonimi:", "variantlar": ["Теплый", "Сухой", "Холодный", "Свежий"], "javob": 2, "tushuntirish": "Горячий (issiq) ↔ Холодный (sovuq)."},
    {"savol": "🇷🇺 'Хороший' so'zining antonimi:", "variantlar": ["Добрый", "Светлый", "Прекрасный", "Плохой"], "javob": 3, "tushuntirish": "Хороший (yaxshi) ↔ Плохой (yomon)."},
    {"savol": "🇷🇺 'Сегодня' so'zining ma'nosi:", "variantlar": ["Bugun", "Kecha", "Ertaga", "Hozir"], "javob": 0, "tushuntirish": "Сегодня = Bugun."},
    {"savol": "🇷🇺 'Завтра' so'zi nimani bildiradi?", "variantlar": ["Bugun", "Ertaga", "Kecha", "Kunduzi"], "javob": 1, "tushuntirish": "Завтра = Ertaga."},
    {"savol": "🇷🇺 'Вчера' so'zining ma'nosi:", "variantlar": ["Ertaga", "Hozir", "Kecha", "Oldin"], "javob": 2, "tushuntirish": "Вчера = Kecha."},
    {"savol": "🇷🇺 'Сейчас' so'zi nimani anglatadi?", "variantlar": ["Keyin", "Ilgari", "Tezda", "Hozir"], "javob": 3, "tushuntirish": "Сейчас = Hozir."},
    {"savol": "🇷🇺 'Всегда' so'zining tarjimasi:", "variantlar": ["Har doim", "Hech qachon", "Ba'zan", "Kamdan-kam"], "javob": 0, "tushuntirish": "Всегда = Har doim."},
    {"savol": "🇷🇺 'Никогда' so'zi nimani bildiradi?", "variantlar": ["Har doim", "Hech qachon", "Ehtimol", "Tez-tez"], "javob": 1, "tushuntirish": "Никогда = Hech qachon."},
    {"savol": "🇷🇺 'Иногда' so'zining tarjimasi:", "variantlar": ["Doim", "Hech qachon", "Ba'zan", "Kechqurun"], "javob": 2, "tushuntirish": "Иногда = Ba'zan, vaqti-vaqti bilan."},
    {"savol": "🇷🇺 'Часто' so'zi nima degani?", "variantlar": ["Kamdan-kam", "Sekin", "Juda oz", "Tez-tez"], "javob": 3, "tushuntirish": "Часто = Tez-tez."},
    {"savol": "🇷🇺 'Спасибо' so'zining ma'nosi:", "variantlar": ["Rahmat", "Iltimos", "Kechirasiz", "Salom"], "javob": 0, "tushuntirish": "Спасибо = Rahmat."},
    {"savol": "🇷🇺 'Пожалуйста' qachon aytiladi?", "variantlar": ["Xayrlashganda", "Iltimos yoki marhamat deganda", "Salomlashganda", "Kechirim so'raganda"], "javob": 1, "tushuntirish": "Пожалуйста = Iltimos / Arzimaydi / Marhamat."},
    {"savol": "🇷🇺 'Здравствуйте' so'zining tarjimasi:", "variantlar": ["Xayr", "Rahmat", "Assalomu alaykum / Salom", "Xush kelibsiz"], "javob": 2, "tushuntirish": "Здравствуйте = Assalomu alaykum."},
    {"savol": "🇷🇺 'До свидания' iborasi nimani bildiradi?", "variantlar": ["Xush kelibsiz", "Kechirasiz", "Rahmat", "Xayr, ko'rishguncha"], "javob": 3, "tushuntirish": "До свидания = Xayr, ko'rishguncha."},
    {"savol": "🇷🇺 'Извините' so'zining tarjimasi:", "variantlar": ["Kechirasiz", "Marhamat", "Rahmat", "Albatta"], "javob": 0, "tushuntirish": "Извините = Kechirasiz."},
    {"savol": "🇷🇺 'Как дела?' iborasining ma'nosi:", "variantlar": ["Qayerdansiz?", "Ishlar qalay? / Qandaysiz?", "Ismingiz nima?", "Qayerga boryapsiz?"], "javob": 1, "tushuntirish": "Как дела? = Ishlar qalay? Ahvolingiz qanday?"},
    {"savol": "🇷🇺 'Сколько это стоит?' nimani anglatadi?", "variantlar": ["Soat necha bo'ldi?", "Qayerda joylashgan?", "Bu qancha turadi (narxi)?", "Qachon ochiladi?"], "javob": 2, "tushuntirish": "Сколько это стоит? = Bu qancha turadi?"},
    {"savol": "🇷🇺 'Где находится...?' savoli nimani so'raydi?", "variantlar": ["Kim bu?", "Qancha vaqt ketadi?", "Narxi qancha?", "Qayerda joylashgan?"], "javob": 3, "tushuntirish": "Где находится...? = ... qayerda joylashgan?"},
    {"savol": "🇷🇺 'Знание' so'zining o'zbekchasi:", "variantlar": ["Bilim", "Kuch", "Aql", "Fikr"], "javob": 0, "tushuntirish": "Знание = Bilim."},
    {"savol": "🇷🇺 'Успех' so'zi nimani anglatadi?", "variantlar": ["Omadsizlik", "Muvaffaqiyat", "Imtihon", "Harakat"], "javob": 1, "tushuntirish": "Успех = Muvaffaqiyat."},
    {"savol": "🇷🇺 'Здоровье' so'zining ma'nosi:", "variantlar": ["Kasallik", "Boylik", "Sog'lik, salomatlik", "Umr"], "javob": 2, "tushuntirish": "Здоровье = Sog'lik, salomatlik."},
    {"savol": "🇷🇺 'Счастье' so'zining tarjimasi:", "variantlar": ["Qayg'u", "G'alaba", "Umid", "Baxt"], "javob": 3, "tushuntirish": "Счастье = Baxt."},
    {"savol": "🇷🇺 'Правда' so'zining tarjimasi:", "variantlar": ["Haqiqat", "Yolg'on", "Xabar", "Savol"], "javob": 0, "tushuntirish": "Правда = Haqiqat."},
    {"savol": "🇷🇺 'Ложь' so'zining antonimi qaysi?", "variantlar": ["Obid", "Правда", "Слово", "Мысль"], "javob": 1, "tushuntirish": "Ложь (yolg'on) ↔ Правда (haqiqat)."},
    {"savol": "🇷🇺 'Мир' so'zi qanday ma'nolarga ega?", "variantlar": ["Faqat urush", "Faqat kosmos", "Tinchlik va Dunyo", "Faqat shahar"], "javob": 2, "tushuntirish": "Мир = Tinchlik hamda Dunyo/Olam ma'nosida keladi."},
    {"savol": "🇷🇺 'Будущее' so'zining o'zbekchasi:", "variantlar": ["O'tmish", "Hozirgi zamon", "Bugungi kun", "Kelajak"], "javob": 3, "tushuntirish": "Будущее = Kelajak."},
    {"savol": "🇷🇺 'Прошлое' so'zining ma'nosi:", "variantlar": ["O'tmish", "Kelajak", "Hozir", "Yil"], "javob": 0, "tushuntirish": "Прошлое = O'tmish."},
    {"savol": "🇷🇺 'Возможность' so'zining tarjimasi:", "variantlar": ["Qiyinchilik", "Imkoniyat", "Majburiyat", "Talab"], "javob": 1, "tushuntirish": "Возможность = Imkoniyat."},
    {"savol": "🇷🇺 'Решение' so'zi nimani bildiradi?", "variantlar": ["Savol", "Muammo", "Qaror yoki Yechim", "Natija"], "javob": 2, "tushuntirish": "Решение = Qaror / Yechim."},
    {"savol": "🇷🇺 'Опыт' so'zining tarjimasi:", "variantlar": ["Yosh", "Ilm", "Qobiliyat", "Tajriba"], "javob": 3, "tushuntirish": "Опыт = Tajriba."},
    {"savol": "🇷🇺 'Понимать' fe'lining ma'nosi:", "variantlar": ["Tushunmoq", "Eshitmoq", "Aytmoq", "Ko'rmoq"], "javob": 0, "tushuntirish": "Понимать = Tushunmoq."},
    {"savol": "🇷🇺 'Помнить' fe'li nima degani?", "variantlar": ["Unitmoq", "Eslab qolmoq, eslamoq", "Qidirmoq", "Topmoq"], "javob": 1, "tushuntirish": "Помнить = Eslamoq, yodda tutmoq."},
    {"savol": "🇷🇺 'Забыть' fe'lining tarjimasi:", "variantlar": ["Eslamoq", "Yozmoq", "Unitmoq", "O'ylamoq"], "javob": 2, "tushuntirish": "Забыть = Unitmoq."},
    {"savol": "🇷🇺 'Развивать' so'zining ma'nosi:", "variantlar": ["Buzmoq", "To'xtatmoq", "Kechiktirmoq", "Rivojlantirmoq"], "javob": 3, "tushuntirish": "Развивать = Rivojlantirmoq."},
    {"savol": "🇷🇺 'Создавать' so'zi nimani bildiradi?", "variantlar": ["Yaratmoq", "Buzmoq", "Yo'qotmoq", "Ko'chirmoq"], "javob": 0, "tushuntirish": "Создавать = Yaratmoq, barpo etmoq."},
    {"savol": "🇷🇺 'Достигать' fe'lining tarjimasi:", "variantlar": ["Yiqilmoq", "Erishmoq", "Qochmoq", "Uxlash"], "javob": 1, "tushuntirish": "Достигать = Erishmoq, maqsadga yetmoq."},
    {"savol": "🇷🇺 'Учиться' fe'li nima degani?", "variantlar": ["Ishlamoq", "O'ynamoq", "O'qimoq, o'rganmoq", "Yashamoq"], "javob": 2, "tushuntirish": "Учиться = O'qimoq, ta'lim olmoq."},
    {"savol": "🇷🇺 'Жить' fe'lining ma'nosi:", "variantlar": ["O'lmoq", "Ketmoq", "Qolmoq", "Yashamoq"], "javob": 3, "tushuntirish": "Жить = Yashamoq."},
    {"savol": "🇷🇺 'Любить' fe'lining o'zbekchasi:", "variantlar": ["Sevmoq, yoqtirmoq", "Nafratlanmoq", "Qo'rqmoq", "Xafa bo'lmoq"], "javob": 0, "tushuntirish": "Любить = Sevmoq, yaxshi ko'rmoq."},
    {"savol": "🇷🇺 'Мы ___ в Ташкенте.' — to'g'ri fe'lni tanlang:", "variantlar": ["живу", "живем", "живет", "живут"], "javob": 1, "tushuntirish": "Мы (biz) bilan 'живем' shakli ishlatiladi."},
    {"savol": "🇷🇺 'Ты ___ по-русски?' — so'roq gapi:", "variantlar": ["говорит", "говорим", "говоришь", "говорят"], "javob": 2, "tushuntirish": "Ты (sen) bilan 'говоришь'."},
    {"savol": "🇷🇺 'Вы ___ чай или кофе?' — to'ldiring:", "variantlar": ["хочу", "хочет", "хотим", "хотите"], "javob": 3, "tushuntirish": "Вы (siz) bilan 'хотите'."},
    {"savol": "🇷🇺 'Один, два, три, ___' — davomini toping:", "variantlar": ["Четыре", "Пять", "Шесть", "Семь"], "javob": 0, "tushuntirish": "1, 2, 3 dan keyin 4 (четыре) keladi."},
    {"savol": "🇷🇺 'Десять' soni o'zbekchada necha?", "variantlar": ["Besh", "O'n", "Yigirma", "Yuz"], "javob": 1, "tushuntirish": "Десять = 10 (o'n)."},
    {"savol": "🇷🇺 'Сто' soni nimani anglatadi?", "variantlar": ["O'n", "Ellik", "Yuz", "Ming"], "javob": 2, "tushuntirish": "Сто = 100 (yuz)."},
    {"savol": "🇷🇺 'Тысяча' so'zining ma'nosi:", "variantlar": ["Yuz", "O'n ming", "Million", "Ming"], "javob": 3, "tushuntirish": "Тысяча = 1000 (ming)."},
    {"savol": "🇷🇺 'Понедельник' haftaning qaysi kuni?", "variantlar": ["Dushanba", "Seshanba", "Chorshanba", "Payshanba"], "javob": 0, "tushuntirish": "Понедельник = Dushanba."},
    {"savol": "🇷🇺 'Вторник' haftaning qaysi kuni?", "variantlar": ["Dushanba", "Seshanba", "Juma", "Shanba"], "javob": 1, "tushuntirish": "Вторник = Seshanba."},
    {"savol": "🇷🇺 'Среда' qaysi kunga to'g'ri keladi?", "variantlar": ["Seshanba", "Payshanba", "Chorshanba", "Juma"], "javob": 2, "tushuntirish": "Среда = Chorshanba."},
    {"savol": "🇷🇺 'Пятница' haftaning qaysi kuni?", "variantlar": ["Payshanba", "Shanba", "Yakshanba", "Juma"], "javob": 3, "tushuntirish": "Пятница = Juma."},
    {"savol": "🇷🇺 'Воскресенье' qaysi kun?", "variantlar": ["Yakshanba", "Shanba", "Juma", "Dushanba"], "javob": 0, "tushuntirish": "Воскресенье = Yakshanba."},
    {"savol": "🇷🇺 'Утро' so'zining ma'nosi:", "variantlar": ["Kechqurun", "Ertalab, tong", "Tush payti", "Tun"], "javob": 1, "tushuntirish": "Утро = Ertalab, tong."},
    {"savol": "🇷🇺 'Вечер' so'zi nimani bildiradi?", "variantlar": ["Ertalab", "Kun", "Kechqurun, oqshom", "Tun"], "javob": 2, "tushuntirish": "Вечер = Kechqurun, oqshom."},
    {"savol": "🇷🇺 'Ночь' so'zining o'zbekchasi:", "variantlar": ["Kunduz", "Tong", "Quyosh", "Tun, kecha"], "javob": 3, "tushuntirish": "Ночь = Tun."},
    {"savol": "🇷🇺 'Лето' yilning qaysi fasli?", "variantlar": ["Yoz", "Qish", "Bahor", "Kuz"], "javob": 0, "tushuntirish": "Лето = Yoz."},
    {"savol": "🇷🇺 'Зима' qaysi fasl?", "variantlar": ["Yoz", "Qish", "Kuz", "Bahor"], "javob": 1, "tushuntirish": "Зима = Qish."},
    {"savol": "🇷🇺 'Весна' so'zining tarjimasi:", "variantlar": ["Qish", "Yoz", "Bahor", "Kuz"], "javob": 2, "tushuntirish": "Весна = Bahor."},
    {"savol": "🇷🇺 'Осень' yilning qaysi fasli?", "variantlar": ["Bahor", "Yoz", "Qish", "Kuz"], "javob": 3, "tushuntirish": "Осень = Kuz."},
    {"savol": "🇷🇺 'Дождь' so'zining tarjimasi:", "variantlar": ["Yomg'ir", "Qor", "Shamol", "Tuman"], "javob": 0, "tushuntirish": "Дождь = Yomg'ir."},
    {"savol": "🇷🇺 'Снег' so'zi nima degani?", "variantlar": ["Yomg'ir", "Qor", "Muz", "Dovul"], "javob": 1, "tushuntirish": "Снег = Qor."},
    {"savol": "🇷🇺 'Ветер' nimani bildiradi?", "variantlar": ["Quyosh", "Bulut", "Shamol", "Chaqaq"], "javob": 2, "tushuntirish": "Ветер = Shamol."},
    {"savol": "🇷🇺 'Облако' so'zining ma'nosi:", "variantlar": ["Osmon", "Yulduz", "Oy", "Bulut"], "javob": 3, "tushuntirish": "Облако = Bulut."},
    {"savol": "🇷🇺 'Красный' qaysi rang?", "variantlar": ["Qizil", "Ko'k", "Yashil", "Sariq"], "javob": 0, "tushuntirish": "Красный = Qizil."},
    {"savol": "🇷🇺 'Синий' qaysi rangni bildiradi?", "variantlar": ["Qizil", "Ko'k", "Oq", "Qora"], "javob": 1, "tushuntirish": "Синий = Ko'k."},
    {"savol": "🇷🇺 'Зеленый' qaysi rang?", "variantlar": ["Sariq", "Jigarrang", "Yashil", "Binafsha"], "javob": 2, "tushuntirish": "Зеленый = Yashil."},
    {"savol": "🇷🇺 'Белый' so'zining ma'nosi:", "variantlar": ["Qora", "Kulrang", "Qizil", "Oq"], "javob": 3, "tushuntirish": "Белый = Oq."},
    {"savol": "🇷🇺 'Черный' so'zi qaysi rang?", "variantlar": ["Qora", "Oq", "Ko'k", "Yashil"], "javob": 0, "tushuntirish": "Черный = Qora."},
    {"savol": "🇷🇺 'Желтый' qaysi rang?", "variantlar": ["Qizil", "Sariq", "Moviy", "Pushti"], "javob": 1, "tushuntirish": "Желтый = Sariq."},
    {"savol": "🇷🇺 'Ни пуха ни пера!' iborasining ma'nosi nima?", "variantlar": ["Ovga borma", "Qushlarni otma", "Omad tilayman! (Imtihonda)", "Ehtiyot bo'l"], "javob": 2, "tushuntirish": "'Ни пуха ни пера' = Omad tilayman! (Javob: К чёрту!)."},
    {"savol": "🇷🇺 'Вешать лапшу на уши' iborasi nimani bildiradi?", "variantlar": ["Taom pishirmoq", "Ovqat bermoq", "Quloq solmaslik", "Aldamoq, yolg'on gapirmoq"], "javob": 3, "tushuntirish": "'Вешать лапшу на уши' = Quloqqa lag'mon ilmoq / Aldamoq."},
    {"savol": "🇷🇺 'Делать из мухи слона' iborasining ma'nosi:", "variantlar": ["Kichik narsani bo'rttirmoq", "Fil sotib olmoq", "Hasharotlarni o'rganmoq", "Katta ish qilmoq"], "javob": 0, "tushuntirish": "'Делать из мухи слона' = Pashshadan fil yasamoq, bo'rttirmoq."},
    {"savol": "🇷🇺 'Семь пятниц на неделе' kimga nisbatan aytiladi?", "variantlar": ["Mehnatkash odamga", "Fikri tez-tez o'zgaradigan odamga", "Dam olishni yaxshi ko'radiganga", "Dindor odamga"], "javob": 1, "tushuntirish": "'Семь пятниц на неделе' = O'zgaruvchan, qarorida turmaydigan odam."},
    {"savol": "🇷🇺 'Убить двух зайцев' iborasi nimani bildiradi?", "variantlar": ["Ov qilish", "Xato qilish", "Bitta ish bilan ikkita natijaga erishmoq", "Vaqtni behuda sarflamoq"], "javob": 2, "tushuntirish": "'Убить двух зайцев' = Bir o'q bilan ikki quyonni urmoq."},
    {"savol": "🇷🇺 'Брать себя в руки' iborasining ma'nosi:", "variantlar": ["Sport bilan shug'ullanmoq", "O'zini ko'tarmoq", "Jismoniy mashq", "O'zini qo'lga olmoq, tinchlanmoq"], "javob": 3, "tushuntirish": "'Брать себя в руки' = O'zini bosmoq, xotirjam bo'lmoq."},
]

# ============================================================
# 🇰🇷 KOREYS TILI TESTLARI (100 ta)
# ============================================================
TEST_QUESTIONS_KO = [
    {"savol": "🇰🇷 '안녕하세요' (Annyeonghaseyo) nimani anglatadi?", "variantlar": ["Assalomu alaykum / Salom", "Xayr", "Rahmat", "Kechirasiz"], "javob": 0, "tushuntirish": "안녕하세요 = Salom / Assalomu alaykum."},
    {"savol": "🇰🇷 '감사합니다' (Gamsahamnida) so'zining ma'nosi:", "variantlar": ["Iltimos", "Rahmat", "Salom", "Xush kelibsiz"], "javob": 1, "tushuntirish": "감사합니다 = Rahmat, tashakkur."},
    {"savol": "🇰🇷 '죄송합니다' (Joesonghamnida) nimani bildiradi?", "variantlar": ["Marhamat", "Salom", "Kechirasiz / Uzr", "Ko'rishguncha"], "javob": 2, "tushuntirish": "죄송합니다 = Kechirasiz, uzr so'rayman."},
    {"savol": "🇰🇷 '네' (Ne) so'zining tarjimasi:", "variantlar": ["Yo'q", "Balki", "Albatta yo'q", "Ha"], "javob": 3, "tushuntirish": "네 = Ha."},
    {"savol": "🇰🇷 '아니요' (Aniyo) nimani bildiradi?", "variantlar": ["Yo'q", "Ha", "Rahmat", "Mayli"], "javob": 0, "tushuntirish": "아니요 = Yo'q."},
    {"savol": "🇰🇷 '물' (Mul) so'zining o'zbekchasi qaysi?", "variantlar": ["Choy", "Suv", "Sut", "Sharbat"], "javob": 1, "tushuntirish": "물 = Suv."},
    {"savol": "🇰🇷 '밥' (Bap) so'zi nimani anglatadi?", "variantlar": ["Non", "Meva", "Guruch / Ovqat", "Go'sht"], "javob": 2, "tushuntirish": "밥 = Guruch yoki umuman ovqat."},
    {"savol": "🇰🇷 '책' (Chaek) so'zining ma'nosi:", "variantlar": ["Daftar", "Qalam", "Stol", "Kitob"], "javob": 3, "tushuntirish": "책 = Kitob."},
    {"savol": "🇰🇷 '집' (Jip) so'zi nima degani?", "variantlar": ["Uy", "Maktab", "Bino", "Xona"], "javob": 0, "tushuntirish": "집 = Uy."},
    {"savol": "🇰🇷 '학교' (Hakgyo) nimani bildiradi?", "variantlar": ["Kutubxona", "Maktab", "Kasalxona", "Bozor"], "javob": 1, "tushuntirish": "학교 = Maktab."},
    {"savol": "🇰🇷 '친구' (Chingu) so'zining tarjimasi:", "variantlar": ["Aka", "Opa", "Do'st", "Qo'shni"], "javob": 2, "tushuntirish": "친구 = Do'st."},
    {"savol": "🇰🇷 '선생님' (Seonsaengnim) kim?", "variantlar": ["Talaba", "Shifokor", "Haydovchi", "O'qituvchi / Ustoz"], "javob": 3, "tushuntirish": "선생님 = O'qituvchi, ustoz."},
    {"savol": "🇰🇷 '학생' (Haksaeng) so'zining ma'nosi:", "variantlar": ["O'quvchi / Talaba", "Ustoz", "Mudir", "Do'st"], "javob": 0, "tushuntirish": "학생 = O'quvchi, talaba."},
    {"savol": "🇰🇷 '사람' (Saram) nimani bildiradi?", "variantlar": ["Hayvon", "Odam / Inson", "Shahar", "Daraxt"], "javob": 1, "tushuntirish": "사람 = Odam, kishi."},
    {"savol": "🇰🇷 '우즈베키스탄 사람' nima degani?", "variantlar": ["Koreys odam", "Rus odam", "O'zbekistonlik odam", "Amerikalik"], "javob": 2, "tushuntirish": "우즈베키스탄 사람 = O'zbekistonlik inson."},
    {"savol": "🇰🇷 '한국' (Hanguk) qaysi davlat?", "variantlar": ["Xitoy", "Yaponiya", "Vyetnam", "Janubiy Koreya"], "javob": 3, "tushuntirish": "한국 = Janubiy Koreya."},
    {"savol": "🇰🇷 '한국어' (Hangugeo) nima?", "variantlar": ["Koreys tili", "Koreys taomi", "Koreya bayrog'i", "Koreys puli"], "javob": 0, "tushuntirish": "한국어 = Koreys tili."},
    {"savol": "🇰🇷 '돈' (Don) so'zining ma'nosi:", "variantlar": ["Vaqt", "Pul", "Kitob", "Oltin"], "javob": 1, "tushuntirish": "돈 = Pul."},
    {"savol": "🇰🇷 '시간' (Sigan) nimani bildiradi?", "variantlar": ["Soat", "Kun", "Vaqt", "Daqiqa"], "javob": 2, "tushuntirish": "시간 = Vaqt."},
    {"savol": "🇰🇷 '오늘' (Oneul) so'zining ma'nosi:", "variantlar": ["Kecha", "Ertaga", "Hozir", "Bugun"], "javob": 3, "tushuntirish": "오늘 = Bugun."},
    {"savol": "🇰🇷 '내일' (Naeil) qaysi kun?", "variantlar": ["Ertaga", "Bugun", "Kecha", "Indinga"], "javob": 0, "tushuntirish": "내일 = Ertaga."},
    {"savol": "🇰🇷 '어제' (Eoje) nimani anglatadi?", "variantlar": ["Ertaga", "Kecha", "Bugun", "O'tgan oy"], "javob": 1, "tushuntirish": "어제 = Kecha."},
    {"savol": "🇰🇷 '지금' (Jigeum) so'zining tarjimasi:", "variantlar": ["Keyin", "Ilgari", "Hozir", "Ertalab"], "javob": 2, "tushuntirish": "지금 = Hozir."},
    {"savol": "🇰🇷 '사과' (Sagwa) so'zi qaysi mevani bildiradi?", "variantlar": ["Nok", "Uzum", "Shaftoli", "Olma"], "javob": 3, "tushuntirish": "사과 = Olma (shuningdek 'uzr' ma'nosi ham bor)."},
    {"savol": "🇰🇷 '우유' (Uyu) so'zining ma'nosi:", "variantlar": ["Sut", "Suv", "Choy", "Qatiq"], "javob": 0, "tushuntirish": "우유 = Sut."},
    {"savol": "🇰🇷 '차' (Cha) nimani bildiradi?", "variantlar": ["Sut", "Choy yoki Mashina", "Non", "Shakar"], "javob": 1, "tushuntirish": "차 = Choy (ichimlik) yoki mashina/avtomobil."},
    {"savol": "🇰🇷 '빵' (Ppang) so'zining tarjimasi:", "variantlar": ["Guruch", "Sho'rva", "Non", "Tuxum"], "javob": 2, "tushuntirish": "빵 = Non."},
    {"savol": "🇰🇷 '고기' (Gogi) nima degani?", "variantlar": ["Baliq", "Sabzavot", "Meva", "Go'sht"], "javob": 3, "tushuntirish": "고기 = Go'sht."},
    {"savol": "🇰🇷 '병원' (Byeongwon) qayer?", "variantlar": ["Shifoxona / Kasalxona", "Maktab", "Dorixona", "Bank"], "javob": 0, "tushuntirish": "병원 = Shifoxona, kasalxona."},
    {"savol": "🇰🇷 '약국' (Yakguk) nimani bildiradi?", "variantlar": ["Bozor", "Dorixona", "Kutubxona", "Mehmonxona"], "javob": 1, "tushuntirish": "약국 = Dorixona."},
    {"savol": "🇰🇷 '식당' (Sikdang) qanday joy?", "variantlar": ["Kino", "Park", "Oshxona / Restoran", "Do'kon"], "javob": 2, "tushuntirish": "식당 = Oshxona, restoran."},
    {"savol": "🇰🇷 '회사' (Hoesa) nimani anglatadi?", "variantlar": ["Zavod", "Universitet", "Uy", "Kompaniya / Firma"], "javob": 3, "tushuntirish": "회사 = Kompaniya, korxona."},
    {"savol": "🇰🇷 Koreys alifbosi nima deb ataladi?", "variantlar": ["Hangul (한글)", "Kanji", "Hanja", "Katakana"], "javob": 0, "tushuntirish": "Koreys alifbosi 'Hangul' (한글) deb ataladi."},
    {"savol": "🇰🇷 '가다' (Gada) fe'lining ma'nosi:", "variantlar": ["Kelmoq", "Bormoq", "O'tirmoq", "Yotmoq"], "javob": 1, "tushuntirish": "가다 = Bormoq, ketmoq."},
    {"savol": "🇰🇷 '오다' (Oda) fe'li nimani bildiradi?", "variantlar": ["Ketmoq", "Yugurmoq", "Kelmoq", "Ko'rmoq"], "javob": 2, "tushuntirish": "오다 = Kelmoq."},
    {"savol": "🇰🇷 '먹다' (Meokda) fe'lining tarjimasi:", "variantlar": ["Ichmoq", "Pishirmoq", "Sotib olmoq", "Yemoq"], "javob": 3, "tushuntirish": "먹다 = Yemoq."},
    {"savol": "🇰🇷 '마시다' (Masida) nimani anglatadi?", "variantlar": ["Ichmoq", "Yemoq", "Kutmoq", "Yuvmoq"], "javob": 0, "tushuntirish": "마시다 = Ichmoq."},
    {"savol": "🇰🇷 '자다' (Jada) fe'li nima degani?", "variantlar": ["Uyg'onmoq", "Uxlamoq", "Yotmoq", "Dam olmoq"], "javob": 1, "tushuntirish": "자다 = Uxlamoq."},
    {"savol": "🇰🇷 '보다' (Boda) fe'lining tarjimasi:", "variantlar": ["Eshitmoq", "Ushlamoq", "Ko'rmoq, qaramoq", "Gapirmoq"], "javob": 2, "tushuntirish": "보다 = Ko'rmoq, qaramoq."},
    {"savol": "🇰🇷 '듣다' (Deutda) fe'li nimani bildiradi?", "variantlar": ["Gapirmoq", "O'qimoq", "Yozmoq", "Eshitmoq, tinglamoq"], "javob": 3, "tushuntirish": "듣다 = Eshitmoq, tinglamoq."},
    {"savol": "🇰🇷 '읽다' (Ikda) so'zining ma'nosi:", "variantlar": ["O'qimoq (kitob)", "Yozmoq", "Chizmoq", "Yodlamoq"], "javob": 0, "tushuntirish": "읽다 = O'qimoq."},
    {"savol": "🇰🇷 '쓰다' (Sseuda) fe'lining ma'nosi:", "variantlar": ["O'qimoq", "Yozmoq / Taqqamoq", "Yuvmoq", "Yopmoq"], "javob": 1, "tushuntirish": "쓰다 = Yozmoq (shuningdek taqmoq, achchiq)."},
    {"savol": "🇰🇷 '만나다' (Mannada) nimani bildiradi?", "variantlar": ["Xayrlashmoq", "Kutmoq", "Uchrashmoq", "Tanishtirmoq"], "javob": 2, "tushuntirish": "만나다 = Uchrashmoq."},
    {"savol": "🇰🇷 '공부하다' (Gongbuhada) fe'lining ma'nosi:", "variantlar": ["Ishlamoq", "Dam olmoq", "O'ynamoq", "Dars qilmoq, o'rganmoq"], "javob": 3, "tushuntirish": "공부하다 = Dars qilmoq, o'qimoq."},
    {"savol": "🇰🇷 '일하다' (Ilhada) nimani anglatadi?", "variantlar": ["Ishlamoq", "Sayohat qilmoq", "Sport qilmoq", "O'qimoq"], "javob": 0, "tushuntirish": "일하다 = Ishlamoq."},
    {"savol": "🇰🇷 '운동하다' (Undonghada) fe'lining tarjimasi:", "variantlar": ["Ovqatlanmoq", "Sport bilan shug'ullanmoq", "Mashina haydamoq", "Uxlamoq"], "javob": 1, "tushuntirish": "운동하다 = Sport/mashq qilmoq."},
    {"savol": "🇰🇷 '전화하다' (Jeonhwahada) nima degani?", "variantlar": ["Xat yozmoq", "Televizor ko'rmoq", "Telefon qilmoq", "Musiqa tinglamoq"], "javob": 2, "tushuntirish": "전화하다 = Telefon qilmoq."},
    {"savol": "🇰🇷 '사다' (Sada) fe'lining tarjimasi:", "variantlar": ["Sotmoq", "Almashtirmoq", "Qarz olmoq", "Sotib olmoq"], "javob": 3, "tushuntirish": "사다 = Sotib olmoq."},
    {"savol": "🇰🇷 '팔다' (Palda) so'zining ma'nosi:", "variantlar": ["Sotmoq", "Sotib olmoq", "Kiyinmoq", "Yechmoq"], "javob": 0, "tushuntirish": "팔다 = Sotmoq."},
    {"savol": "🇰🇷 '크다' (Keuda) qanday sifat?", "variantlar": ["Kichik", "Katta", "Uzun", "Qisqa"], "javob": 1, "tushuntirish": "크다 = Katta."},
    {"savol": "🇰🇷 '작다' (Jakda) so'zining ma'nosi:", "variantlar": ["Katta", "Keng", "Kichik", "Tor"], "javob": 2, "tushuntirish": "작다 = Kichik."},
    {"savol": "🇰🇷 '많다' (Manta) nimani bildiradi?", "variantlar": ["Kam", "Og'ir", "Yengil", "Ko'p"], "javob": 3, "tushuntirish": "많다 = Ko'p."},
    {"savol": "🇰🇷 '적다' (Jeokda) nimani anglatadi?", "variantlar": ["Kam / Oz", "Ko'p", "Baland", "Past"], "javob": 0, "tushuntirish": "적다 = Kam, oz."},
    {"savol": "🇰🇷 '좋다' (Jota) so'zining tarjimasi:", "variantlar": ["Yomon", "Yaxshi", "Qiyin", "Oson"], "javob": 1, "tushuntirish": "좋다 = Yaxshi."},
    {"savol": "🇰🇷 '나쁘다' (Nappeuda) qanday ma'no beradi?", "variantlar": ["Chiroyli", "Yaxshi", "Yomon", "Shirin"], "javob": 2, "tushuntirish": "나쁘다 = Yomon."},
    {"savol": "🇰🇷 '예쁘다' (Yeppeuda) so'zining ma'nosi:", "variantlar": ["Qo'rqinchli", "Semiz", "Aqlli", "Chiroyli"], "javob": 3, "tushuntirish": "예쁘다 = Chiroyli, go'zal."},
    {"savol": "🇰🇷 '맛있다' (Masitta) nimani bildiradi?", "variantlar": ["Mazali", "Baxshida", "Achchiq", "Shirin emas"], "javob": 0, "tushuntirish": "맛있다 = Mazali, shirin."},
    {"savol": "🇰🇷 '맛없다' (Madeopda) so'zining ma'nosi:", "variantlar": ["Juda mazali", "Mazasi yo'q / Bemaza", "Sho'r", "Issiq"], "javob": 1, "tushuntirish": "맛없다 = Mazasiz, bemaza."},
    {"savol": "🇰🇷 '비싸다' (Bissada) narx haqida nima deydi?", "variantlar": ["Arzon", "Bepul", "Qimmat", "Chegirma"], "javob": 2, "tushuntirish": "비싸다 = Qimmat."},
    {"savol": "🇰🇷 '싸다' (Ssada) so'zining ma'nosi:", "variantlar": ["Qimmat", "Og'ir", "Katta", "Arzon"], "javob": 3, "tushuntirish": "싸다 = Arzon."},
    {"savol": "🇰🇷 '어디' (Eodi) so'rog'i nimani anglatadi?", "variantlar": ["Qayerda / Qayerga", "Qachon", "Nima", "Kim"], "javob": 0, "tushuntirish": "어디 = Qayerda / Qayerga."},
    {"savol": "🇰🇷 '언제' (Eonje) qaysi savol?", "variantlar": ["Qayerda", "Qachon", "Nega", "Qanday"], "javob": 1, "tushuntirish": "언제 = Qachon."},
    {"savol": "🇰🇷 '누구' (Nugu) nimani so'raydi?", "variantlar": ["Nima", "Qayer", "Kim", "Qancha"], "javob": 2, "tushuntirish": "누구 = Kim."},
    {"savol": "🇰🇷 '무엇 / 뭐' (Mueot / Mwo) nima degani?", "variantlar": ["Kim", "Qachon", "Qaysi", "Nima"], "javob": 3, "tushuntirish": "무엇 / 뭐 = Nima."},
    {"savol": "🇰🇷 '왜' (Wae) savol so'zining tarjimasi:", "variantlar": ["Nima uchun / Nega", "Qayerda", "Qanday", "Qancha"], "javob": 0, "tushuntirish": "왜 = Nega, nima uchun."},
    {"savol": "🇰🇷 '어떻게' (Eotteoke) nimani anglatadi?", "variantlar": ["Qachon", "Qanday qilib", "Kim bilan", "Qayerdan"], "javob": 1, "tushuntirish": "어떻게 = Qanday qilib."},
    {"savol": "🇰🇷 '얼마예요?' (Eolmayeyo?) savoli nima haqida?", "variantlar": ["Soat necha?", "Qayerga ketayapsiz?", "Qancha turadi (narxi)?", "Kim bu?"], "javob": 2, "tushuntirish": "얼마예요? = Narxi qancha?"},
    {"savol": "🇰🇷 '이름이 뭐예요?' (Ireumi mwoyeyo?) nima degani?", "variantlar": ["Qayerdansiz?", "Necha yoshdasiz?", "Kasbingiz nima?", "Ismingiz nima?"], "javob": 3, "tushuntirish": "이름이 뭐예요? = Ismingiz nima?"},
    {"savol": "🇰🇷 '일, 이, 삼, ___' — davomini toping (Xitoy-koreys sanoq):", "variantlar": ["사 (Sa - 4)", "오 (O - 5)", "육 (Yuk - 6)", "칠 (Chil - 7)"], "javob": 0, "tushuntirish": "1(일), 2(이), 3(삼) dan keyin 4(사) keladi."},
    {"savol": "🇰🇷 '십' (Sip) soni o'zbekchada necha?", "variantlar": ["Besh", "O'n (10)", "Yigirma", "Yuz"], "javob": 1, "tushuntirish": "십 = 10 (o'n)."},
    {"savol": "🇰🇷 '백' (Baek) sonining ma'nosi:", "variantlar": ["O'n", "Ming", "Yuz (100)", "O'n ming"], "javob": 2, "tushuntirish": "백 = 100 (yuz)."},
    {"savol": "🇰🇷 '천' (Cheon) soni qaysi?", "variantlar": ["Yuz", "O'n", "O'n ming", "Ming (1000)"], "javob": 3, "tushuntirish": "천 = 1,000 (ming)."},
    {"savol": "🇰🇷 '만' (Man) soni qancha?", "variantlar": ["10,000 (O'n ming)", "1,000", "100,000", "1,000,000"], "javob": 0, "tushuntirish": "만 = 10,000 (o'n ming)."},
    {"savol": "🇰🇷 '하나, 둘, ___' — sof koreyscha sanashda 3 nima deyiladi?", "variantlar": ["넷 (Net)", "셋 (Set)", "다섯 (Daseot)", "여섯 (Yeoseot)"], "javob": 1, "tushuntirish": "1(하나), 2(둘), 3(셋)."},
    {"savol": "🇰🇷 '월요일' (Woryoil) haftaning qaysi kuni?", "variantlar": ["Seshanba", "Chorshanba", "Dushanba", "Juma"], "javob": 2, "tushuntirish": "월요일 = Dushanba."},
    {"savol": "🇰🇷 '일요일' (Iryoil) qaysi kun?", "variantlar": ["Dushanba", "Shanba", "Juma", "Yakshanba"], "javob": 3, "tushuntirish": "일요일 = Yakshanba."},
    {"savol": "🇰🇷 '봄' (Bom) fasli o'zbekchada nima?", "variantlar": ["Bahor", "Yoz", "Kuz", "Qish"], "javob": 0, "tushuntirish": "봄 = Bahor."},
    {"savol": "🇰🇷 '여름' (Yeoreum) qaysi fasl?", "variantlar": ["Bahor", "Yoz", "Qish", "Kuz"], "javob": 1, "tushuntirish": "여름 = Yoz."},
    {"savol": "🇰🇷 '가을' (Gaeul) so'zining tarjimasi:", "variantlar": ["Yoz", "Qish", "Kuz", "Bahor"], "javob": 2, "tushuntirish": "가을 = Kuz."},
    {"savol": "🇰🇷 '겨울' (Gyeoul) qaysi fasl?", "variantlar": ["Yoz", "Bahor", "Kuz", "Qish"], "javob": 3, "tushuntirish": "겨울 = Qish."},
    {"savol": "🇰🇷 '날씨' (Nalssi) so'zining ma'nosi:", "variantlar": ["Ob-havo", "Fasl", "Kun", "Hafta"], "javob": 0, "tushuntirish": "날씨 = Ob-havo."},
    {"savol": "🇰🇷 '비' (Bi) so'zi nimani bildiradi?", "variantlar": ["Qor", "Yomg'ir", "Shamol", "Quyosh"], "javob": 1, "tushuntirish": "비 = Yomg'ir."},
    {"savol": "🇰🇷 '눈' (Nun) qanday ma'nolarga ega?", "variantlar": ["Quloq va burun", "Qo'l va oyoq", "Qor va Ko'z", "Suv va muz"], "javob": 2, "tushuntirish": "눈 = Qor yoki Ko'z ma'nosini beradi."},
    {"savol": "🇰🇷 '가족' (Gajok) so'zining ma'nosi:", "variantlar": ["Do'stlar", "Hamkasblar", "Qo'shnilar", "Oila"], "javob": 3, "tushuntirish": "가족 = Oila."},
    {"savol": "🇰🇷 '아버지' (Abeoji) kim?", "variantlar": ["Ota", "Ona", "Aka", "Tog'a"], "javob": 0, "tushuntirish": "아버지 = Ota."},
    {"savol": "🇰🇷 '어머니' (Eomeoni) kimni bildiradi?", "variantlar": ["Opa", "Ona", "Buvijon", "Xola"], "javob": 1, "tushuntirish": "어머니 = Ona."},
    {"savol": "🇰🇷 '형' (Hyeong) so'zini kim aytadi?", "variantlar": ["Qiz bola akasiga", "Ona o'g'liga", "O'g'il bola o'zidan katta akasiga", "Kichik singilga"], "javob": 2, "tushuntirish": "형 = O'g'il bola katta akasiga aytadi."},
    {"savol": "🇰🇷 '오빠' (Oppa) so'zini kim aytadi?", "variantlar": ["O'g'il bola akasiga", "Ota o'g'liga", "Ustozga", "Qiz bola o'zidan katta erkakka/akasiga"], "javob": 3, "tushuntirish": "오빠 = Qiz bola o'zidan katta akasiga aytadi."},
    {"savol": "🇰🇷 '누나' (Nuna) so'zining ma'nosi:", "variantlar": ["O'g'il bolaning katta opasi", "Qiz bolaning opasi", "Singil", "Ona"], "javob": 0, "tushuntirish": "누나 = O'g'il bolaning opasi."},
    {"savol": "🇰🇷 '언니' (Eonni) kimga aytiladi?", "variantlar": ["O'g'il bola akasiga", "Qiz bola o'zidan katta opasiga", "Uka uchun", "Ota uchun"], "javob": 1, "tushuntirish": "언니 = Qiz bola o'zidan katta opasiga aytadi."},
    {"savol": "🇰🇷 '동생' (Dongsaeng) nimani bildiradi?", "variantlar": ["Katta aka", "Katta opa", "Uka yoki singil", "Do'st"], "javob": 2, "tushuntirish": "동생 = Uka yoki singil."},
    {"savol": "🇰🇷 '머리' (Meori) inson tanasining qaysi qismi?", "variantlar": ["Qo'l", "Oyoq", "Yurak", "Bosh / Soch"], "javob": 3, "tushuntirish": "머리 = Bosh yoki soch."},
    {"savol": "🇰🇷 '손' (Son) nimani bildiradi?", "variantlar": ["Qo'l", "Oyoq", "Yuz", "Tish"], "javob": 0, "tushuntirish": "손 = Qo'l (panja)."},
    {"savol": "🇰🇷 '발' (Bal) tananing qaysi qismi?", "variantlar": ["Qo'l", "Oyoq", "Ko'z", "Qorin"], "javob": 1, "tushuntirish": "발 = Oyoq."},
    {"savol": "🇰🇷 '안녕히 계세요' (Annyeonghi gyeseyo) qachon aytiladi?", "variantlar": ["Ketayotgan odamga", "Kutib olganda", "Qolayotgan odamga (ketuvchi shaxs aytadi)", "Kechirim so'raganda"], "javob": 2, "tushuntirish": "Ketayotgan kishi xonada qoluvchiga 'Yaxshi qoling' deb aytadi."},
    {"savol": "🇰🇷 '안녕히 가세요' (Annyeonghi gaseyo) nima degani?", "variantlar": ["Salom", "Xush kelibsiz", "Kechirasiz", "Yaxshi boring (ketayotgan odamga aytiladi)"], "javob": 3, "tushuntirish": "Xonada qoluvchi ketayotganga 'Yaxshi boring' deb aytadi."},
    {"savol": "🇰🇷 '화이팅 / 파이팅' (Hwaiting / Paiting) nimani bildiradi?", "variantlar": ["Omad! / Olg'a! / G'ayrat qil!", "To'xta", "Yordam bering", "Xayr"], "javob": 0, "tushuntirish": "화이팅 = Olg'a! Omad tilayman! Bardam bo'l!"},
    {"savol": "🇰🇷 '대박' (Daebak) jargon so'zi nimani anglatadi?", "variantlar": ["Yomon xabar", "Ajoyib! / Qoyilmaqom! / Super!", "Qimmat narsa", "Kech qolish"], "javob": 1, "tushuntirish": "대박 = Qoyil! Ajoyib! Bomba!"},
    {"savol": "🇰🇷 '진짜' (Jinjja) so'zi nimani bildiradi?", "variantlar": ["Yolg'on", "Kechikish", "Rostdanmi? / Haqiqatan", "Mayli"], "javob": 2, "tushuntirish": "진짜 = Haqiqatan, rostdan ham."},
    {"savol": "🇰🇷 '괜찮아요' (Gwaenchanhayo) iborasining ma'nosi:", "variantlar": ["Xavfli", "Bo'lmaydi", "Qimmat", "Hammasi joyida / Hechqisi yo'q"], "javob": 3, "tushuntirish": "괜찮아요 = Hechqisi yo'q, xavotir olmang, yaxshi."},
]

# ============================================================
# 🇹🇷 TURK TILI TESTLARI (100 ta)
# ============================================================
TEST_QUESTIONS_TR = [
    {"savol": "🇹🇷 'Merhaba' so'zining ma'nosi nima?", "variantlar": ["Salom", "Xayr", "Rahmat", "Iltimos"], "javob": 0, "tushuntirish": "Merhaba = Salom / Assalomu alaykum."},
    {"savol": "🇹🇷 'Teşekkür ederim' nimani anglatadi?", "variantlar": ["Kechirasiz", "Rahmat / Tashakkur", "Salom", "Xush kelibsiz"], "javob": 1, "tushuntirish": "Teşekkür ederim = Rahmat, tashakkur bildiraman."},
    {"savol": "🇹🇷 'Lütfen' so'zining tarjimasi:", "variantlar": ["Xayr", "Ha", "Iltimos", "Yo'q"], "javob": 2, "tushuntirish": "Lütfen = Iltimos."},
    {"savol": "🇹🇷 'Özür dilerim' iborasi nimani bildiradi?", "variantlar": ["Rahmat", "Marhamat", "Salom", "Kechirasiz / Uzr so'rayman"], "javob": 3, "tushuntirish": "Özür dilerim = Kechirim so'rayman, uzr."},
    {"savol": "🇹🇷 'Evet' so'zining ma'nosi:", "variantlar": ["Ha", "Yo'q", "Balki", "Hech qachon"], "javob": 0, "tushuntirish": "Evet = Ha."},
    {"savol": "🇹🇷 'Hayır' nimani anglatadi?", "variantlar": ["Ha", "Yo'q", "Yaxshi", "Albatta"], "javob": 1, "tushuntirish": "Hayır = Yo'q."},
    {"savol": "🇹🇷 'Su' so'zining o'zbekcha tarjimasi:", "variantlar": ["Non", "Choy", "Suv", "Sut"], "javob": 2, "tushuntirish": "Su = Suv."},
    {"savol": "🇹🇷 'Ekmek' so'zi nimani bildiradi?", "variantlar": ["Go'sht", "Meva", "Sho'rva", "Non"], "javob": 3, "tushuntirish": "Ekmek = Non."},
    {"savol": "🇹🇷 'Çay' so'zining ma'nosi:", "variantlar": ["Choy", "Kofe", "Suv", "Sharbat"], "javob": 0, "tushuntirish": "Çay = Choy."},
    {"savol": "🇹🇷 'Süt' so'zining tarjimasi:", "variantlar": ["Qatiq", "Sut", "Yog'", "Pishloq"], "javob": 1, "tushuntirish": "Süt = Sut."},
    {"savol": "🇹🇷 'Kitap' so'zi nima degani?", "variantlar": ["Daftar", "Qalam", "Kitob", "Lug'at"], "javob": 2, "tushuntirish": "Kitap = Kitob."},
    {"savol": "🇹🇷 'Ev' so'zining o'zbekchasi:", "variantlar": ["Shahar", "Bino", "Ko'cha", "Uy"], "javob": 3, "tushuntirish": "Ev = Uy."},
    {"savol": "🇹🇷 'Okul' so'zining ma'nosi:", "variantlar": ["Maktab", "Bog'cha", "Universitet", "Kutubxona"], "javob": 0, "tushuntirish": "Okul = Maktab."},
    {"savol": "🇹🇷 'Öğretmen' kim?", "variantlar": ["Talaba", "O'qituvchi", "Shifokor", "Muhandis"], "javob": 1, "tushuntirish": "Öğretmen = O'qituvchi."},
    {"savol": "🇹🇷 'Öğrenci' so'zining tarjimasi:", "variantlar": ["Ustoz", "Direktor", "O'quvchi / Talaba", "Hamkasb"], "javob": 2, "tushuntirish": "Öğrenci = O'quvchi, talaba."},
    {"savol": "🇹🇷 'Arkadaş' nimani anglatadi?", "variantlar": ["Dushman", "Qo'shni", "Aka", "Do'st"], "javob": 3, "tushuntirish": "Arkadaş = Do'st, o'rtoq."},
    {"savol": "🇹🇷 'Para' so'zining ma'nosi:", "variantlar": ["Pul", "Vaqt", "Boylik", "Qarz"], "javob": 0, "tushuntirish": "Para = Pul."},
    {"savol": "🇹🇷 'Zaman' nimani bildiradi?", "variantlar": ["Soat", "Vaqt", "Kun", "Yil"], "javob": 1, "tushuntirish": "Zaman = Vaqt."},
    {"savol": "🇹🇷 'Bugün' so'zining tarjimasi:", "variantlar": ["Kecha", "Ertaga", "Bugun", "Hozir"], "javob": 2, "tushuntirish": "Bugün = Bugun."},
    {"savol": "🇹🇷 'Yarın' qaysi kunni bildiradi?", "variantlar": ["Bugun", "Kecha", "Indinga", "Ertaga"], "javob": 3, "tushuntirish": "Yarın = Ertaga."},
    {"savol": "🇹🇷 'Dün' so'zining ma'nosi:", "variantlar": ["Kecha", "Bugun", "Ertaga", "O'tgan hafta"], "javob": 0, "tushuntirish": "Dün = Kecha."},
    {"savol": "🇹🇷 'Şimdi' nimani anglatadi?", "variantlar": ["Keyin", "Hozir", "Ilgari", "Tezda"], "javob": 1, "tushuntirish": "Şimdi = Hozir."},
    {"savol": "🇹🇷 'Hoş geldiniz' iborasining javobi qaysi?", "variantlar": ["Güle güle", "Günaydın", "Hoş bulduk", "İyi geceler"], "javob": 2, "tushuntirish": "'Hoş geldiniz' (Xush kelibsiz) ga 'Hoş bulduk' (Xush ko'rdik) deb javob beriladi."},
    {"savol": "🇹🇷 'Güle güle' qachon aytiladi?", "variantlar": ["Tongda salomlashganda", "Ovqatlanganda", "Uxlashdan oldin", "Kuzatayotganda (Xayr deganda)"], "javob": 3, "tushuntirish": "Güle güle = Xayr, yaxshi boring (kuzatuvchi aytadi)."},
    {"savol": "🇹🇷 'Günaydın' so'zining ma'nosi:", "variantlar": ["Xayrli tong", "Xayrli kech", "Xayrli tun", "Kuningiz xayrli o'tsin"], "javob": 0, "tushuntirish": "Günaydın = Xayrli tong."},
    {"savol": "🇹🇷 'İyi akşamlar' qachon aytiladi?", "variantlar": ["Ertalab", "Kechqurun (Xayrli kech)", "Peshinda", "Tongda"], "javob": 1, "tushuntirish": "İyi akşamlar = Xayrli kech."},
    {"savol": "🇹🇷 'İyi geceler' nimani anglatadi?", "variantlar": ["Xayrli kun", "Xayrli tong", "Xayrli tun", "Oq yo'l"], "javob": 2, "tushuntirish": "İyi geceler = Xayrli tun."},
    {"savol": "🇹🇷 'Nasılsınız?' savolining ma'nosi:", "variantlar": ["Ismingiz nima?", "Qayerdansiz?", "Necha yoshdasiz?", "Qandaysiz? / Ishlar qalay?"], "javob": 3, "tushuntirish": "Nasılsınız? = Ahvolingiz qanday? Qandaysiz?"},
    {"savol": "🇹🇷 'İyiyim' so'zining ma'nosi:", "variantlar": ["Yaxshiman", "Yomonman", "Charchadim", "Bilmayman"], "javob": 0, "tushuntirish": "İyiyim = Yaxshiman."},
    {"savol": "🇹🇷 'Adınız ne?' savoli nimani so'raydi?", "variantlar": ["Qayerdansiz?", "Ismingiz nima?", "Nima qilyapsiz?", "Qayerga boryapsiz?"], "javob": 1, "tushuntirish": "Adınız ne? = Ismingiz nima?"},
    {"savol": "🇹🇷 'Nerelisiniz?' nimani anglatadi?", "variantlar": ["Qayerda yashaysiz?", "Qayerga ketayapsiz?", "Qayerdansiz? (Qaysi shahardan/mamlakatdan)", "Kasbingiz nima?"], "javob": 2, "tushuntirish": "Nerelisiniz? = Qayerdansiz?"},
    {"savol": "🇹🇷 'Ne kadar?' savoli nimani so'raydi?", "variantlar": ["Kim bu?", "Qayerda?", "Qachon?", "Qancha? (narxi yoki miqdori)"], "javob": 3, "tushuntirish": "Ne kadar? = Qancha? Narxi qancha?"},
    {"savol": "🇹🇷 'Nerede?' so'rog'ining ma'nosi:", "variantlar": ["Qayerda?", "Qachon?", "Nega?", "Qanday?"], "javob": 0, "tushuntirish": "Nerede? = Qayerda?"},
    {"savol": "🇹🇷 'Ne zaman?' nimani bildiradi?", "variantlar": ["Qayerda?", "Qachon?", "Kim?", "Nima?"], "javob": 1, "tushuntirish": "Ne zaman? = Qachon?"},
    {"savol": "🇹🇷 'Neden / Niçin?' savoli nima haqida?", "variantlar": ["Qanday?", "Qayerga?", "Nima uchun? / Nega?", "Qachon?"], "javob": 2, "tushuntirish": "Neden / Niçin = Nega, nima uchun?"},
    {"savol": "🇹🇷 'Nasıl?' so'rog'i nimani anglatadi?", "variantlar": ["Qayerda?", "Qancha?", "Kim bilan?", "Qanday?"], "javob": 3, "tushuntirish": "Nasıl? = Qanday?"},
    {"savol": "🇹🇷 'Büyük' so'zining ma'nosi:", "variantlar": ["Katta", "Kichik", "Uzun", "Qisqa"], "javob": 0, "tushuntirish": "Büyük = Katta."},
    {"savol": "🇹🇷 'Küçük' so'zining antonimi (qarama-qarshisi):", "variantlar": ["Dar", "Büyük", "Kısa", "Ağır"], "javob": 1, "tushuntirish": "Küçük (kichik) ↔ Büyük (katta)."},
    {"savol": "🇹🇷 'Güzel' so'zining tarjimasi:", "variantlar": ["Xunuk", "Aqlli", "Chiroyli / Go'zal", "Mehribon"], "javob": 2, "tushuntirish": "Güzel = Chiroyli, go'zal."},
    {"savol": "🇹🇷 'Çirkin' nimani anglatadi?", "variantlar": ["Chiroyli", "Katta", "Semiz", "Xunuk / Beo'xshov"], "javob": 3, "tushuntirish": "Çirkin = Xunuk."},
    {"savol": "🇹🇷 'Sıcak' so'zining ma'nosi:", "variantlar": ["Issiq", "Sovuq", "Iliq", "Muzdek"], "javob": 0, "tushuntirish": "Sıcak = Issiq."},
    {"savol": "🇹🇷 'Soğuk' nimani bildiradi?", "variantlar": ["Issiq", "Sovuq", "Shamolli", "Yomg'irli"], "javob": 1, "tushuntirish": "Soğuk = Sovuq."},
    {"savol": "🇹🇷 'Pahalı' so'zi narx haqida nima deydi?", "variantlar": ["Arzon", "Bepul", "Qimmat", "Chegirmali"], "javob": 2, "tushuntirish": "Pahalı = Qimmat."},
    {"savol": "🇹🇷 'Ucuz' so'zining ma'nosi:", "variantlar": ["Qimmat", "Qiyin", "Kam", "Arzon"], "javob": 3, "tushuntirish": "Ucuz = Arzon."},
    {"savol": "🇹🇷 'Kolay' so'zining tarjimasi:", "variantlar": ["Oson", "Qiyin", "Tez", "Sekin"], "javob": 0, "tushuntirish": "Kolay = Oson."},
    {"savol": "🇹🇷 'Zor' so'zining antonimi qaysi?", "variantlar": ["Ağır", "Kolay", "Büyük", "Güçlü"], "javob": 1, "tushuntirish": "Zor (qiyin) ↔ Kolay (oson)."},
    {"savol": "🇹🇷 'Yeni' so'zining ma'nosi:", "variantlar": ["Eski", "Buzuq", "Yangi", "Toza"], "javob": 2, "tushuntirish": "Yeni = Yangi."},
    {"savol": "🇹🇷 'Eski' so'zining tarjimasi:", "variantlar": ["Yangi", "Qimmat", "Arzon", "Eski"], "javob": 3, "tushuntirish": "Eski = Eski."},
    {"savol": "🇹🇷 'Gitmek' fe'lining ma'nosi:", "variantlar": ["Ketmoq / Bormoq", "Kelmoq", "O'tirmoq", "Uxlamoq"], "javob": 0, "tushuntirish": "Gitmek = Ketmoq, bormoq."},
    {"savol": "🇹🇷 'Gelmek' fe'li nimani bildiradi?", "variantlar": ["Ketmoq", "Kelmoq", "Ko'rmoq", "Kutmoq"], "javob": 1, "tushuntirish": "Gelmek = Kelmoq."},
    {"savol": "🇹🇷 'Yemek' so'zi qanday ma'nolarga ega?", "variantlar": ["Faqat ichmoq", "Faqat pishirmoq", "Yemoq (fe'l) hamda Taom / Ovqat (ot)", "Kechikmoq"], "javob": 2, "tushuntirish": "Yemek = Taom (ovqat) yoki yemoq harakati."},
    {"savol": "🇹🇷 'İçmek' fe'lining tarjimasi:", "variantlar": ["Yemoq", "Uxlamoq", "Yozmoq", "Ichmoq"], "javob": 3, "tushuntirish": "İçmek = Ichmoq."},
    {"savol": "🇹🇷 'Uyumak' so'zining ma'nosi:", "variantlar": ["Uxlamoq", "Uyg'onmoq", "Dam olmoq", "Yugurmoq"], "javob": 0, "tushuntirish": "Uyumak = Uxlamoq."},
    {"savol": "🇹🇷 'Uyanmak' nimani bildiradi?", "variantlar": ["Uxlamoq", "Uyg'onmoq", "Yuvinmoq", "Kiyinmoq"], "javob": 1, "tushuntirish": "Uyanmak = Uyg'onmoq."},
    {"savol": "🇹🇷 'Görmek' fe'lining tarjimasi:", "variantlar": ["Eshitmoq", "Gapirmoq", "Ko'rmoq", "Sezmoq"], "javob": 2, "tushuntirish": "Görmek = Ko'rmoq."},
    {"savol": "🇹🇷 'Duymak' so'zining ma'nosi:", "variantlar": ["Ko'rmoq", "Ushlamoq", "Tatib ko'rmoq", "Eshitmoq / Tuyg'uni sezmoq"], "javob": 3, "tushuntirish": "Duymak = Eshitmoq, his qilmoq."},
    {"savol": "🇹🇷 'Konuşmak' nimani bildiradi?", "variantlar": ["Gapirmoq / So'zlashmoq", "Jim turmoq", "Quloq solmoq", "Yozmoq"], "javob": 0, "tushuntirish": "Konuşmak = Gapirmoq, so'zlashmoq."},
    {"savol": "🇹🇷 'Okumak' fe'lining tarjimasi:", "variantlar": ["Yozmoq", "O'qimoq", "Chizmoq", "Yodlamoq"], "javob": 1, "tushuntirish": "Okumak = O'qimoq."},
    {"savol": "🇹🇷 'Yazmak' fe'li nima degani?", "variantlar": ["O'qimoq", "Eshitmoq", "Yozmoq", "Ko'rmoq"], "javob": 2, "tushuntirish": "Yazmak = Yozmoq."},
    {"savol": "🇹🇷 'Çalışmak' nimani bildiradi?", "variantlar": ["Dam olmoq", "O'ynamoq", "Sayohat qilmoq", "Ishlamoq / Dars qilmoq"], "javob": 3, "tushuntirish": "Çalışmak = Ishlamoq, mehnat qilmoq, o'qimoq."},
    {"savol": "🇹🇷 'Sevmek' so'zining ma'nosi:", "variantlar": ["Sevmoq / Yaxshi ko'rmoq", "Nafratlanmoq", "Qo'rqmoq", "Xafa bo'lmoq"], "javob": 0, "tushuntirish": "Sevmek = Sevmoq, yaxshi ko'rmoq."},
    {"savol": "🇹🇷 'Anlamak' fe'lining tarjimasi:", "variantlar": ["Unutmoq", "Tushunmoq", "Eslamoq", "Qidirmoq"], "javob": 1, "tushuntirish": "Anlamak = Tushunmoq, anglamoq."},
    {"savol": "🇹🇷 'Unutmak' so'zining ma'nosi:", "variantlar": ["Eslab qolmoq", "Yozib qo'ymoq", "Unutmoq", "Topmoq"], "javob": 2, "tushuntirish": "Unutmak = Unutmoq, esdan chiqarmoq."},
    {"savol": "🇹🇷 'Hatırlamak' nimani bildiradi?", "variantlar": ["Yo'qotmoq", "Unutmoq", "Kechikmoq", "Eslamoq / Yodga olmoq"], "javob": 3, "tushuntirish": "Hatırlamak = Eslamoq, xotirlamoq."},
    {"savol": "🇹🇷 'Bilmek' fe'lining ma'nosi:", "variantlar": ["Bilmoq", "Bilmaslik", "O'rganmoq", "So'ramoq"], "javob": 0, "tushuntirish": "Bilmek = Bilmoq."},
    {"savol": "🇹🇷 'Ben kitap okuyorum.' gapi qaysi zamonda?", "variantlar": ["O'tgan zamon", "Hozirgi zamon (Şimdiki zaman)", "Kelasi zamon", "Noaniq o'tgan zamon"], "javob": 1, "tushuntirish": "-iyor qo'shimchasi hozirgi davomli zamonni bildiradi."},
    {"savol": "🇹🇷 'Biz sinemaya gideceğiz.' qaysi zamonda?", "variantlar": ["Hozirgi zamon", "O'tgan zamon", "Kelasi zamon (Gelecek zaman)", "Keng zamon"], "javob": 2, "tushuntirish": "-ecek/-acak kelasi zamon qo'shimchasi: gideceğiz = boramiz."},
    {"savol": "🇹🇷 'O dün geldi.' gapining ma'nosi:", "variantlar": ["U ertaga keladi", "U hozir kelyapti", "U kelmadi", "U kecha keldi"], "javob": 3, "tushuntirish": "O dün geldi = U kecha keldi."},
    {"savol": "🇹🇷 'Bir, iki, üç, ___' — 4 turkcha nima deyiladi?", "variantlar": ["Dört", "Beş", "Altı", "Yedi"], "javob": 0, "tushuntirish": "1(Bir), 2(İki), 3(Üç) dan so'ng 4(Dört) keladi."},
    {"savol": "🇹🇷 'On' soni o'zbekchada necha?", "variantlar": ["Besh", "O'n (10)", "Yigirma", "Yuz"], "javob": 1, "tushuntirish": "On = 10 (o'n)."},
    {"savol": "🇹🇷 'Yüz' so'zi qanday ma'nolarga ega?", "variantlar": ["Faqat son", "Faqat tana a'zosi", "Yuz (100) va Inson yuzi", "O'n va Ming"], "javob": 2, "tushuntirish": "Yüz = 100 soni hamda inson yuzi (surat) ma'nosida."},
    {"savol": "🇹🇷 'Bin' soni qancha?", "variantlar": ["Yuz", "O'n ming", "Million", "Ming (1000)"], "javob": 3, "tushuntirish": "Bin = 1,000 (ming)."},
    {"savol": "🇹🇷 'Pazartesi' haftaning qaysi kuni?", "variantlar": ["Dushanba", "Seshanba", "Juma", "Shanba"], "javob": 0, "tushuntirish": "Pazartesi = Dushanba."},
    {"savol": "🇹🇷 'Salı' haftaning qaysi kuni?", "variantlar": ["Dushanba", "Seshanba", "Chorshanba", "Payshanba"], "javob": 1, "tushuntirish": "Salı = Seshanba."},
    {"savol": "🇹🇷 'Çarşamba' qaysi kunga to'g'ri keladi?", "variantlar": ["Seshanba", "Payshanba", "Chorshanba", "Juma"], "javob": 2, "tushuntirish": "Çarşamba = Chorshanba."},
    {"savol": "🇹🇷 'Cuma' haftaning qaysi kuni?", "variantlar": ["Payshanba", "Shanba", "Yakshanba", "Juma"], "javob": 3, "tushuntirish": "Cuma = Juma."},
    {"savol": "🇹🇷 'Pazar' qaysi kun?", "variantlar": ["Yakshanba", "Shanba", "Juma", "Bozor kuni emas"], "javob": 0, "tushuntirish": "Pazar = Yakshanba."},
    {"savol": "🇹🇷 'İlkbahar' fasli o'zbekchada nima?", "variantlar": ["Yoz", "Bahor", "Kuz", "Qish"], "javob": 1, "tushuntirish": "İlkbahar = Bahor."},
    {"savol": "🇹🇷 'Yaz' fasli nimani anglatadi?", "variantlar": ["Bahor", "Kuz", "Yoz", "Qish"], "javob": 2, "tushuntirish": "Yaz = Yoz fasli."},
    {"savol": "🇹🇷 'Sonbahar' qaysi fasl?", "variantlar": ["Bahor", "Yoz", "Qish", "Kuz"], "javob": 3, "tushuntirish": "Sonbahar = Kuz."},
    {"savol": "🇹🇷 'Kış' faslining tarjimasi:", "variantlar": ["Qish", "Yoz", "Bahor", "Kuz"], "javob": 0, "tushuntirish": "Kış = Qish."},
    {"savol": "🇹🇷 'Hava' so'zining ma'nosi:", "variantlar": ["Suv", "Ob-havo / Havo", "Quyosh", "Bulut"], "javob": 1, "tushuntirish": "Hava = Havo, ob-havo."},
    {"savol": "🇹🇷 'Yağmur' nimani bildiradi?", "variantlar": ["Qor", "Dovul", "Yomg'ir", "Tuman"], "javob": 2, "tushuntirish": "Yağmur = Yomg'ir."},
    {"savol": "🇹🇷 'Kar' so'zi nima degani?", "variantlar": ["Muz", "Yomg'ir", "Shamol", "Qor"], "javob": 3, "tushuntirish": "Kar = Qor."},
    {"savol": "🇹🇷 'Güneş' so'zining tarjimasi:", "variantlar": ["Quyosh", "Oy", "Yulduz", "Osmon"], "javob": 0, "tushuntirish": "Güneş = Quyosh."},
    {"savol": "🇹🇷 'Ay' qanday ma'nolarga ega?", "variantlar": ["Faqat fasl", "Oy (osmondagi va kalendardagi)", "Faqat quyosh", "Faqat kun"], "javob": 1, "tushuntirish": "Ay = Osmondagi Oy hamda 30 kunlik kalendar oyi."},
    {"savol": "🇹🇷 'Yıldız' nimani bildiradi?", "variantlar": ["Oy", "Quyosh", "Yulduz", "Koinot"], "javob": 2, "tushuntirish": "Yıldız = Yulduz."},
    {"savol": "🇹🇷 'Aile' so'zining o'zbekchasi:", "variantlar": ["Qarindosh", "Do'st", "Qo'shni", "Oila"], "javob": 3, "tushuntirish": "Aile = Oila."},
    {"savol": "🇹🇷 'Baba' so'zining ma'nosi:", "variantlar": ["Ota", "Ona", "Aka", "Bobo"], "javob": 0, "tushuntirish": "Baba = Ota."},
    {"savol": "🇹🇷 'Anne' kimni bildiradi?", "variantlar": ["Opa", "Ona", "Buvijon", "Xola"], "javob": 1, "tushuntirish": "Anne = Ona."},
    {"savol": "🇹🇷 'Kardeş' nimani anglatadi?", "variantlar": ["Do'st", "Tog'a", "Aka-uka / Opa-singil", "Ota-ona"], "javob": 2, "tushuntirish": "Kardeş = Qardosh, uka, singil."},
    {"savol": "🇹🇷 'Kırmızı' qaysi rang?", "variantlar": ["Ko'k", "Yashil", "Sariq", "Qizil"], "javob": 3, "tushuntirish": "Kırmızı = Qizil."},
    {"savol": "🇹🇷 'Mavi' rangining tarjimasi:", "variantlar": ["Moviy / Ko'k", "Yashil", "Qora", "Oq"], "javob": 0, "tushuntirish": "Mavi = Moviy, ko'k."},
    {"savol": "🇹🇷 'Yeşil' so'zi qaysi rang?", "variantlar": ["Sariq", "Yashil", "Qizil", "Binafsha"], "javob": 1, "tushuntirish": "Yeşil = Yashil."},
    {"savol": "🇹🇷 'Beyaz' so'zining ma'nosi:", "variantlar": ["Qora", "Kulrang", "Oq", "Jigarrang"], "javob": 2, "tushuntirish": "Beyaz = Oq."},
    {"savol": "🇹🇷 'Siyah' qaysi rangni bildiradi?", "variantlar": ["Oq", "Ko'k", "Yashil", "Qora"], "javob": 3, "tushuntirish": "Siyah = Qora."},
    {"savol": "🇹🇷 'Kolay gelsin' iborasi qachon aytiladi?", "variantlar": ["Ishlayotgan odamga yengillik tilaganda", "Uxlashga ketayotganga", "Ovqatlanayotganga", "Xayrlashganda"], "javob": 0, "tushuntirish": "Kolay gelsin = Ishingiz oson bo'lsin, charchamang."},
    {"savol": "🇹🇷 'Afiyet olsun' qachon aytiladi?", "variantlar": ["Tongda", "Ovqatlanayotganda (Yoqimli ishtaha)", "Kechirim so'raganda", "Xarid qilganda"], "javob": 1, "tushuntirish": "Afiyet olsun = Yoqimli ishtaha / Osh bo'lsin."},
    {"savol": "🇹🇷 'Geçmiş olsun' iborasining ma'nosi:", "variantlar": ["Tabriklayman", "Xush kelibsiz", "Tuzalib keting / O'tib ketsin (betob odamga)", "Xayrli bo'lsin"], "javob": 2, "tushuntirish": "Geçmiş olsun = O'tib ketsin, tezroq shifo toping."},
    {"savol": "🇹🇷 'Gözün aydın' iborasi qachon ishlatiladi?", "variantlar": ["Kasal bo'lganda", "Ko'z shifokorida", "Kech qolganda", "Kutilgan yaxshi xabar kelganda (Ko'zingiz oydin)"], "javob": 3, "tushuntirish": "Gözün aydın = Ko'zingiz oydin! Muborak bo'lsin!"},
]


# ============================================================
# 🧮 MATEMATIKA TESTLARI (100 ta)
# ============================================================
TEST_QUESTIONS_MATH = [
    {"savol": "🧮 45 + 55 × 2 ifodaning qiymatini toping.", "variantlar": ["155", "200", "145", "165"], "javob": 0, "tushuntirish": "Avval ko'paytirish: 55 × 2 = 110. Keyin 45 + 110 = 155."},
    {"savol": "🧮 250 - 150 ÷ 5 ifodaning qiymati necha?", "variantlar": ["20", "220", "240", "180"], "javob": 1, "tushuntirish": "150 ÷ 5 = 30. 250 - 30 = 220."},
    {"savol": "🧮 12 × 15 ko'paytma necha bo'ladi?", "variantlar": ["160", "175", "180", "190"], "javob": 2, "tushuntirish": "12 × 15 = 180."},
    {"savol": "🧮 (18 + 12) × (25 - 15) = ?", "variantlar": ["200", "250", "280", "300"], "javob": 3, "tushuntirish": "30 × 10 = 300."},
    {"savol": "🧮 2 ning 6-darajasi (2⁶) nechiga teng?", "variantlar": ["64", "32", "128", "16"], "javob": 0, "tushuntirish": "2⁶ = 64."},
    {"savol": "🧮 144 sonining kvadrat ildizi (√144) necha?", "variantlar": ["14", "12", "16", "11"], "javob": 1, "tushuntirish": "12² = 144, demak √144 = 12."},
    {"savol": "🧮 7³ ifodaning qiymatini toping.", "variantlar": ["323", "333", "343", "353"], "javob": 2, "tushuntirish": "7 × 7 × 7 = 343."},
    {"savol": "🧮 1000 ÷ 8 ifodaning natijasi qanday?", "variantlar": ["115", "120", "135", "125"], "javob": 3, "tushuntirish": "1000 ÷ 8 = 125."},
    {"savol": "🧮 999 + 888 + 111 + 1 ifodani qulay usulda hisoblang.", "variantlar": ["1999", "2000", "1998", "2100"], "javob": 0, "tushuntirish": "(999 + 1) + (888 + 111) = 1000 + 999 = 1999."},
    {"savol": "🧮 15 ning kvadrati nechaga teng?", "variantlar": ["215", "225", "235", "245"], "javob": 1, "tushuntirish": "15² = 225."},
    {"savol": "🧮 (-15) + (-27) yig'indisi nechaga teng?", "variantlar": ["-40", "-38", "-42", "-44"], "javob": 2, "tushuntirish": "-(15 + 27) = -42."},
    {"savol": "🧮 (-8) × (-12) ko'paytma nimaga teng?", "variantlar": ["-96", "-84", "84", "96"], "javob": 3, "tushuntirish": "(-8) × (-12) = +96."},
    {"savol": "🧮 84 ÷ (-7) bo'linmani hisoblang.", "variantlar": ["-12", "12", "-14", "14"], "javob": 0, "tushuntirish": "84 ÷ (-7) = -12."},
    {"savol": "🧮 √(5² + 12²) ifodaning qiymatini toping.", "variantlar": ["15", "13", "17", "14"], "javob": 1, "tushuntirish": "5² = 25, 12² = 144. 25 + 144 = 169. √169 = 13."},
    {"savol": "🧮 3⁴ ÷ 3² ifodaning qiymati necha?", "variantlar": ["3", "6", "9", "27"], "javob": 2, "tushuntirish": "3⁴⁻² = 3² = 9."},
    {"savol": "🧮 5! (5 faktorial) qiymati qancha?", "variantlar": ["60", "100", "150", "120"], "javob": 3, "tushuntirish": "5! = 1 × 2 × 3 × 4 × 5 = 120."},
    {"savol": "🧮 EKUK(12, 18) — eng kichik umumiy karralisini toping.", "variantlar": ["36", "24", "72", "18"], "javob": 0, "tushuntirish": "12 va 18 ga bo'linadigan eng kichik son 36."},
    {"savol": "🧮 EKUB(36, 48) — eng katta umumiy bo'luvchisini toping.", "variantlar": ["6", "12", "18", "24"], "javob": 1, "tushuntirish": "36 va 48 ning umumiy bo'luvchisi 12."},
    {"savol": "🧮 2³ × 5² ko'paytma nechaga teng?", "variantlar": ["100", "150", "200", "250"], "javob": 2, "tushuntirish": "8 × 25 = 200."},
    {"savol": "🧮 Qaysi son 9 ga qoldiqsiz bo'linadi?", "variantlar": ["1234", "5431", "7218", "8129"], "javob": 2, "tushuntirish": "7 + 2 + 1 + 8 = 18 (9 ga bo'linadi)."},
    {"savol": "🧮 Tenglamani yeching: 2x + 7 = 19", "variantlar": ["x = 6", "x = 5", "x = 7", "x = 8"], "javob": 0, "tushuntirish": "2x = 19 - 7 = 12 => x = 6."},
    {"savol": "🧮 Tenglamani yeching: 5x - 15 = 2x + 6", "variantlar": ["x = 5", "x = 7", "x = 6", "x = 8"], "javob": 1, "tushuntirish": "3x = 21 => x = 7."},
    {"savol": "🧮 3(x - 4) = 18 bo'lsa, x ning qiymati necha?", "variantlar": ["8", "9", "10", "11"], "javob": 2, "tushuntirish": "x - 4 = 6 => x = 10."},
    {"savol": "🧮 x² - 25 = 0 tenglamaning musbat ildizini toping.", "variantlar": ["2", "3", "4", "5"], "javob": 3, "tushuntirish": "x² = 25 => x = 5 (yoki -5)."},
    {"savol": "🧮 (a + b)² formulasining to'g'ri yoyilmasi qaysi?", "variantlar": ["a² + 2ab + b²", "a² + ab + b²", "a² + b²", "a² - 2ab + b²"], "javob": 0, "tushuntirish": "(a + b)² = a² + 2ab + b²."},
    {"savol": "🧮 a² - b² ifoda qanday ko'paytuvchilarga ajraladi?", "variantlar": ["(a - b)²", "(a - b)(a + b)", "(a + b)²", "a(a - b)"], "javob": 1, "tushuntirish": "a² - b² = (a - b)(a + b)."},
    {"savol": "🧮 Agar x = 3, y = -2 bo'lsa, 2x² - 3y ifodaning qiymati necha?", "variantlar": ["21", "22", "24", "20"], "javob": 2, "tushuntirish": "2(9) - 3(-2) = 18 + 6 = 24."},
    {"savol": "🧮 Tenglamani yeching: x / 4 + 5 = 12", "variantlar": ["24", "32", "30", "28"], "javob": 3, "tushuntirish": "x / 4 = 7 => x = 28."},
    {"savol": "🧮 x² - 7x + 12 = 0 tenglamaning ildizlari yig'indisi necha (Viyet)?", "variantlar": ["7", "12", "-7", "-12"], "javob": 0, "tushuntirish": "Viyet teoremasiga ko'ra x₁ + x₂ = -(-7) = 7."},
    {"savol": "🧮 x² - 5x + 6 = 0 tenglama ildizlarini toping.", "variantlar": ["1 va 6", "2 va 3", "-2 va -3", "3 va 4"], "javob": 1, "tushuntirish": "(x - 2)(x - 3) = 0 => x = 2 va x = 3."},
    {"savol": "🧮 Proporsiyadan noma'lumni toping: 3 / 8 = x / 32", "variantlar": ["10", "11", "12", "14"], "javob": 2, "tushuntirish": "x = (3 × 32) / 8 = 12."},
    {"savol": "🧮 4^(x) = 64 bo'lsa, x nechaga teng?", "variantlar": ["1", "2", "4", "3"], "javob": 3, "tushuntirish": "4³ = 64, shuning uchun x = 3."},
    {"savol": "🧮 |x - 3| = 7 tenglamaning eng kichik ildizini toping.", "variantlar": ["-4", "-10", "4", "10"], "javob": 0, "tushuntirish": "x - 3 = 7 => x = 10; x - 3 = -7 => x = -4. Eng kichigi -4."},
    {"savol": "🧮 (x + 3)(x - 3) = ?", "variantlar": ["x² - 6", "x² - 9", "x² + 9", "x² - 6x + 9"], "javob": 1, "tushuntirish": "Kvadratlar ayirmasi: x² - 3² = x² - 9."},
    {"savol": "🧮 Agar 2x + 3y = 13 va y = 3 bo'lsa, x nechaga teng?", "variantlar": ["1", "3", "2", "4"], "javob": 2, "tushuntirish": "2x + 9 = 13 => 2x = 4 => x = 2."},
    {"savol": "🧮 √x + 4 = 9 bo'lsa, x necha?", "variantlar": ["5", "16", "20", "25"], "javob": 3, "tushuntirish": "√x = 5 => x = 25."},
    {"savol": "🧮 2a + 4a - 3a + 5a soddalashtiring:", "variantlar": ["8a", "7a", "9a", "6a"], "javob": 0, "tushuntirish": "(2 + 4 - 3 + 5)a = 8a."},
    {"savol": "🧮 2⁻³ darajaning qiymati necha?", "variantlar": ["1/6", "1/8", "-6", "-8"], "javob": 1, "tushuntirish": "2⁻³ = 1 / 2³ = 1/8."},
    {"savol": "🧮 Sonning 3 baravari bilan uning 7 qo'shilgani 28 ga teng. Bu sonni toping.", "variantlar": ["5", "6", "7", "8"], "javob": 2, "tushuntirish": "3x + 7 = 28 => 3x = 21 => x = 7."},
    {"savol": "🧮 log₂ 32 ning qiymatini hisoblang.", "variantlar": ["3", "4", "6", "5"], "javob": 3, "tushuntirish": "2⁵ = 32, demak log₂ 32 = 5."},
    {"savol": "🧮 1/2 + 1/3 ifodaning qiymati qancha?", "variantlar": ["5/6", "2/5", "1/5", "5/5"], "javob": 0, "tushuntirish": "Umumiy maxraj 6: 3/6 + 2/6 = 5/6."},
    {"savol": "🧮 3/4 - 1/8 kasrlar ayirmasini toping.", "variantlar": ["2/4", "5/8", "1/2", "3/8"], "javob": 1, "tushuntirish": "6/8 - 1/8 = 5/8."},
    {"savol": "🧮 2/5 × 15/4 ko'paytmani hisoblang.", "variantlar": ["1/2", "2", "3/2", "5/4"], "javob": 2, "tushuntirish": "(2 × 15) / (5 × 4) = 30/20 = 3/2."},
    {"savol": "🧮 3/7 ÷ 6/14 bo'linmani toping.", "variantlar": ["2", "1/2", "3/4", "1"], "javob": 3, "tushuntirish": "3/7 × 14/6 = (3 × 14) / (7 × 6) = 42/42 = 1."},
    {"savol": "🧮 200 sonining 25 foizi necha?", "variantlar": ["50", "40", "60", "75"], "javob": 0, "tushuntirish": "200 × 0.25 = 50."},
    {"savol": "🧮 Qaysi sonning 20 foizi 40 ga teng?", "variantlar": ["150", "200", "250", "300"], "javob": 1, "tushuntirish": "x × 0.2 = 40 => x = 200."},
    {"savol": "🧮 500 so'mlik tovar 20% chegirma bilan sotildi. Yangi narxi qancha?", "variantlar": ["420 so'm", "450 so'm", "400 so'm", "380 so'm"], "javob": 2, "tushuntirish": "Chegirma: 500 × 0.2 = 100. 500 - 100 = 400 so'm."},
    {"savol": "🧮 0.75 kasr oddiy kasrda qanday yoziladi?", "variantlar": ["1/2", "2/3", "4/5", "3/4"], "javob": 3, "tushuntirish": "0.75 = 75/100 = 3/4."},
    {"savol": "🧮 1/5 qismi foizda qanchaga to'g'ri keladi?", "variantlar": ["20%", "25%", "15%", "10%"], "javob": 0, "tushuntirish": "1/5 × 100% = 20%."},
    {"savol": "🧮 2 butun 1/2 sonini noto'g'ri kasrga aylantiring.", "variantlar": ["4/2", "5/2", "3/2", "6/2"], "javob": 1, "tushuntirish": "(2 × 2 + 1) / 2 = 5/2."},
    {"savol": "🧮 0.4 × 0.25 ko'paytma necha bo'ladi?", "variantlar": ["0.01", "0.08", "0.1", "1.0"], "javob": 2, "tushuntirish": "0.4 × 0.25 = 0.1."},
    {"savol": "🧮 3.6 ÷ 0.6 bo'linmani toping.", "variantlar": ["0.6", "60", "0.06", "6"], "javob": 3, "tushuntirish": "36 ÷ 6 = 6."},
    {"savol": "🧮 80 soni 25% ga oshirilsa, natija necha bo'ladi?", "variantlar": ["100", "105", "95", "110"], "javob": 0, "tushuntirish": "80 + 80 × 0.25 = 80 + 20 = 100."},
    {"savol": "🧮 150 sonining 60 foizini toping.", "variantlar": ["80", "90", "100", "75"], "javob": 1, "tushuntirish": "150 × 0.6 = 90."},
    {"savol": "🧮 3/10 + 0.4 yig'indisi nechaga teng?", "variantlar": ["0.5", "0.6", "0.7", "0.8"], "javob": 2, "tushuntirish": "3/10 = 0.3. 0.3 + 0.4 = 0.7."},
    {"savol": "🧮 Sinfdagi 30 o'quvchidan 18 tasi qizlar. Qizlar necha foizni tashkil qiladi?", "variantlar": ["50%", "55%", "65%", "60%"], "javob": 3, "tushuntirish": "(18 / 30) × 100% = 60%."},
    {"savol": "🧮 1/4 + 1/2 + 1/8 yig'indini hisoblang.", "variantlar": ["7/8", "5/8", "6/8", "3/8"], "javob": 0, "tushuntirish": "2/8 + 4/8 + 1/8 = 7/8."},
    {"savol": "🧮 100 soni 10% ga oshirildi, so'ng 10% ga kamaytirildi. Natija qancha?", "variantlar": ["100", "99", "101", "98"], "javob": 1, "tushuntirish": "100 -> 110. 110 - 11 = 99."},
    {"savol": "🧮 40 sonining qanday foizini 10 tashkil qiladi?", "variantlar": ["20%", "30%", "25%", "15%"], "javob": 2, "tushuntirish": "(10 / 40) × 100% = 25%."},
    {"savol": "🧮 5/8 kasr o'nli kasrda qanday ifodalanadi?", "variantlar": ["0.58", "0.65", "0.725", "0.625"], "javob": 3, "tushuntirish": "5 ÷ 8 = 0.625."},
    {"savol": "🧮 Uchburchakning barcha ichki burchaklari yig'indisi necha gradus?", "variantlar": ["180°", "360°", "90°", "270°"], "javob": 0, "tushuntirish": "Har qanday uchburchak ichki burchaklari yig'indisi 180° ga teng."},
    {"savol": "🧮 To'g'ri to'rtburchakning tomonlari 6 cm va 8 cm. Uning yuzini toping.", "variantlar": ["28 cm²", "48 cm²", "24 cm²", "56 cm²"], "javob": 1, "tushuntirish": "S = a × b = 6 × 8 = 48 cm²."},
    {"savol": "🧮 Tomoni 5 cm bo'lgan kvadratning perimetri necha cm?", "variantlar": ["15 cm", "25 cm", "20 cm", "30 cm"], "javob": 2, "tushuntirish": "P = 4a = 4 × 5 = 20 cm."},
    {"savol": "🧮 Katetlari 3 va 4 bo'lgan to'g'ri burchakli uchburchak gipotenuzasini toping.", "variantlar": ["6", "7", "8", "5"], "javob": 3, "tushuntirish": "c² = 3² + 4² = 9 + 16 = 25 => c = 5."},
    {"savol": "🧮 Doiraning radiusi 7 cm. Aylananing uzunligini toping (π ≈ 22/7).", "variantlar": ["44 cm", "22 cm", "88 cm", "154 cm"], "javob": 0, "tushuntirish": "C = 2πr = 2 × (22/7) × 7 = 44 cm."},
    {"savol": "🧮 Radiusi 3 cm bo'lgan doiraning yuzini toping (π = 3.14).", "variantlar": ["18.84 cm²", "28.26 cm²", "9.42 cm²", "31.4 cm²"], "javob": 1, "tushuntirish": "S = πr² = 3.14 × 9 = 28.26 cm²."},
    {"savol": "🧮 Teng tomonli uchburchakning har bir burchagi necha gradus?", "variantlar": ["45°", "90°", "60°", "30°"], "javob": 2, "tushuntirish": "180° ÷ 3 = 60°."},
    {"savol": "🧮 To'rtburchakning ichki burchaklari yig'indisi necha gradus?", "variantlar": ["180°", "270°", "300°", "360°"], "javob": 3, "tushuntirish": "Har qanday qavariq to'rtburchak ichki burchaklari yig'indisi 360°."},
    {"savol": "🧮 Tomonlari 7 cm, 8 cm, 9 cm bo'lgan uchburchak perimetri qancha?", "variantlar": ["24 cm", "22 cm", "26 cm", "25 cm"], "javob": 0, "tushuntirish": "P = 7 + 8 + 9 = 24 cm."},
    {"savol": "🧮 Katetlari 6 cm va 8 cm bo'lgan to'g'ri burchakli uchburchak yuzini toping.", "variantlar": ["48 cm²", "24 cm²", "14 cm²", "28 cm²"], "javob": 1, "tushuntirish": "S = (a × b) / 2 = (6 × 8) / 2 = 24 cm²."},
    {"savol": "🧮 Rombning diagonallari 10 cm va 12 cm. Uning yuzi necha cm²?", "variantlar": ["120 cm²", "50 cm²", "60 cm²", "40 cm²"], "javob": 2, "tushuntirish": "S = (d₁ × d₂) / 2 = (10 × 12) / 2 = 60 cm²."},
    {"savol": "🧮 Kubning qirrasi 4 cm. Uning hajmini (V) toping.", "variantlar": ["16 cm³", "48 cm³", "32 cm³", "64 cm³"], "javob": 3, "tushuntirish": "V = a³ = 4³ = 64 cm³."},
    {"savol": "🧮 Trapetsiyaning asoslari 6 cm va 10 cm, balandligi 5 cm. Yuzini toping.", "variantlar": ["40 cm²", "80 cm²", "30 cm²", "50 cm²"], "javob": 0, "tushuntirish": "S = ((a + b) / 2) × h = ((6 + 10) / 2) × 5 = 40 cm²."},
    {"savol": "🧮 Qo'shni burchaklardan biri 70° bo'lsa, ikkinchisi necha gradus?", "variantlar": ["20°", "110°", "90°", "70°"], "javob": 1, "tushuntirish": "Qo'shni burchaklar yig'indisi 180°: 180° - 70° = 110°."},
    {"savol": "🧮 Vertikal burchaklar haqida qaysi fikr to'g'ri?", "variantlar": ["Yig'indisi 180°", "Biri ikkinchisidan katta", "Ular o'zaro teng", "Yig'indisi 90°"], "javob": 2, "tushuntirish": "Vertikal burchaklar har doim o'zaro teng bo'ladi."},
    {"savol": "🧮 O'tkir burchakning qiymati qanday oraliqda bo'ladi?", "variantlar": ["90° dan katta", "180° ga teng", "0° dan kichik", "0° va 90° orasida"], "javob": 3, "tushuntirish": "0° < α < 90° bo'lgan burchak o'tkir burchak deyiladi."},
    {"savol": "🧮 Gipotenuzasi 10, bitta kateti 6 bo'lgan to'g'ri burchakli uchburchakning ikkinchi katetini toping.", "variantlar": ["8", "7", "9", "5"], "javob": 0, "tushuntirish": "b² = 10² - 6² = 100 - 36 = 64 => b = 8."},
    {"savol": "🧮 Muntazam oltiburchakning nechta simmetriya o'qi bor?", "variantlar": ["3", "6", "12", "4"], "javob": 1, "tushuntirish": "Muntazam n-burchakning n ta simmetriya o'qi bo'ladi (6 ta)."},
    {"savol": "🧮 Tomoni 6 cm bo'lgan kvadratning yuzi necha cm²?", "variantlar": ["24 cm²", "30 cm²", "36 cm²", "42 cm²"], "javob": 2, "tushuntirish": "S = a² = 6² = 36 cm²."},
    {"savol": "🧮 Yoyiq burchakning gradus o'lchovi necha?", "variantlar": ["90°", "270°", "360°", "180°"], "javob": 3, "tushuntirish": "Yoyiq burchak 180° ga teng."},
    {"savol": "🧮 Mashina 60 km/soat tezlik bilan 3.5 soatda necha km yo'l bosadi?", "variantlar": ["210 km", "200 km", "180 km", "240 km"], "javob": 0, "tushuntirish": "S = v × t = 60 × 3.5 = 210 km."},
    {"savol": "🧮 Poezd 360 km masofani 4 soatda bosib o'tdi. Uning o'rtacha tezligi qancha?", "variantlar": ["80 km/soat", "90 km/soat", "100 km/soat", "75 km/soat"], "javob": 1, "tushuntirish": "v = S / t = 360 / 4 = 90 km/soat."},
    {"savol": "🧮 Ota 36 yoshda, o'g'li 12 yoshda. Necha yil oldin ota o'g'lidan 4 marta katta bo'lgan?", "variantlar": ["2 yil", "3 yil", "4 yil", "5 yil"], "javob": 2, "tushuntirish": "(36 - x) = 4(12 - x) => 36 - x = 48 - 4x => 3x = 12 => x = 4."},
    {"savol": "🧮 4 nafar ishchi ishni 6 kunda tugatadi. Shu ishni 8 nafar ishchi necha kunda tugatadi?", "variantlar": ["4 kun", "2 kun", "5 kun", "3 kun"], "javob": 3, "tushuntirish": "Teskari proporsiya: 4 × 6 = 8 × x => 24 = 8x => x = 3 kun."},
    {"savol": "🧮 Ketma-ketlikdagi keyingi sonni toping: 2, 4, 8, 16, 32, ?", "variantlar": ["64", "48", "56", "128"], "javob": 0, "tushuntirish": "Har bir son 2 ga ko'payib bormoqda: 32 × 2 = 64."},
    {"savol": "🧮 Ketma-ketlikdagi keyingi sonni toping: 1, 4, 9, 16, 25, ?", "variantlar": ["30", "36", "49", "32"], "javob": 1, "tushuntirish": "Kvadratlar: 1², 2², 3², 4², 5², 6² = 36."},
    {"savol": "🧮 O'yin suyagi (zarracha) tashlanganda 6 tushish ehtimolligi qancha?", "variantlar": ["1/2", "1/3", "1/6", "1/4"], "javob": 2, "tushuntirish": "Jami 6 ta tomon, 6 raqami bitta: P = 1/6."},
    {"savol": "🧮 Qutida 5 ta oq va 3 ta qora shar bor. Tasodifan olingan sharning oq bo'lish ehtimolligi:", "variantlar": ["3/8", "5/3", "1/2", "5/8"], "javob": 3, "tushuntirish": "P = 5 / (5 + 3) = 5/8."},
    {"savol": "🧮 3 ta kitobni javonga necha xil usulda terish mumkin?", "variantlar": ["6 xil", "3 xil", "9 xil", "12 xil"], "javob": 0, "tushuntirish": "P₃ = 3! = 1 × 2 × 3 = 6 xil usulda."},
    {"savol": "🧮 5, 8, 12, 15 sonlarining o'rta arifmetigini toping.", "variantlar": ["9", "10", "11", "8"], "javob": 1, "tushuntirish": "(5 + 8 + 12 + 15) / 4 = 40 / 4 = 10."},
    {"savol": "🧮 7 kishining har biri bir-biri bilan qo'l berib ko'rishdi. Jami nechta ko'rishish bo'lgan?", "variantlar": ["28 ta", "14 ta", "21 ta", "42 ta"], "javob": 2, "tushuntirish": "N(N - 1)/2 = 7 × 6 / 2 = 21 ta."},
    {"savol": "🧮 Bir sonning 4 baravaridan 10 ni ayirsak 50 chiqadi. Bu son qaysi?", "variantlar": ["12", "14", "16", "15"], "javob": 3, "tushuntirish": "4x - 10 = 50 => 4x = 60 => x = 15."},
    {"savol": "🧮 Sayyoh kuniga 15 km yuradi. U 120 km masofani necha kunda bosib o'tadi?", "variantlar": ["8 kun", "7 kun", "9 kun", "10 kun"], "javob": 0, "tushuntirish": "120 ÷ 15 = 8 kunda."},
    {"savol": "🧮 1 dan 100 gacha bo'lgan sonlar orasida nechta tub son bor?", "variantlar": ["20 ta", "25 ta", "30 ta", "24 ta"], "javob": 1, "tushuntirish": "1 dan 100 gacha aniq 25 ta tub son mavjud (2, 3, 5, 7, ..., 97)."},
    {"savol": "🧮 1, 1, 2, 3, 5, 8, 13, ? — Fibonachchi ketma-ketligining keyingi hadi necha?", "variantlar": ["18", "20", "21", "24"], "javob": 2, "tushuntirish": "Oldingi ikki son yig'indisi: 8 + 13 = 21."},
    {"savol": "🧮 1 soat 45 minut necha minutga teng?", "variantlar": ["100 minut", "115 minut", "95 minut", "105 minut"], "javob": 3, "tushuntirish": "60 + 45 = 105 minut."},
    {"savol": "🧮 Hovuzni 1-quvur 4 soatda, 2-quvur 12 soatda to'ldiradi. Ikkalasi birgalikda necha soatda to'ldiradi?", "variantlar": ["3 soat", "2 soat", "4 soat", "6 soat"], "javob": 0, "tushuntirish": "1/4 + 1/12 = 3/12 + 1/12 = 4/12 = 1/3 => 3 soat."},
    {"savol": "🧮 15% foyda bilan 230 ming so'mga sotilgan tovarning asl narxi qancha bo'lgan?", "variantlar": ["190 ming", "200 ming", "210 ming", "205 ming"], "javob": 1, "tushuntirish": "1.15x = 230 => x = 200 ming so'm."},
    {"savol": "🧮 Qavariq beshburchakning barcha ichki burchaklari yig'indisi qancha?", "variantlar": ["360°", "450°", "540°", "720°"], "javob": 2, "tushuntirish": "(n - 2) × 180° = 3 × 180° = 540°."},
    {"savol": "🧮 200 ning 40% ning 50% i nechaga teng?", "variantlar": ["30", "50", "45", "40"], "javob": 3, "tushuntirish": "200 × 0.4 × 0.5 = 40."},
]
# Lug'at ko'rinishida yig'ilgan testlar:
TEST_QUESTIONS = {
    "en": TEST_QUESTIONS_EN,
    "ru": TEST_QUESTIONS_RU,
    "ko": TEST_QUESTIONS_KO,
    "tr": TEST_QUESTIONS_TR,
    "math": TEST_QUESTIONS_MATH,
}

TEST_LANG_NAMES = {
    "en": "🇬🇧 Ingliz tili",
    "ru": "🇷🇺 Rus tili",
    "ko": "🇰🇷 Koreys tili",
    "tr": "🇹🇷 Turk tili",
    "math": "🧮 Matematika",
}
